import { render, screen, waitFor } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { describe, expect, it } from "vitest";

import { AILabel, AILabelExplanation } from "../ai-label";

describe("AILabel — non-interactive marker", () => {
    it("renders a static marker with the 'AI' text and no button/tab stop", () => {
        render(<AILabel />);
        // No popover content → no interactive button.
        expect(screen.queryByRole("button")).not.toBeInTheDocument();
        expect(screen.getByText("AI")).toBeInTheDocument();
    });

    it("icon-only marker still exposes an accessible name containing 'AI'", () => {
        render(<AILabel label={null} ariaLabel="AI generated" />);
        // Visually-hidden text provides the name even with no visible label.
        expect(screen.getByText("AI generated")).toBeInTheDocument();
    });
});

describe("AILabel — interactive explainability popover", () => {
    const explanation = (
        <AILabelExplanation
            states={[{ label: "AI-authored", tone: "info" }]}
            confidence={{ label: "High", method: "llm-judge" }}
            grounding={[{ title: "Source.pdf", href: "#" }]}
            model={{ model: "claude-opus-4-8", at: "2h ago", retrieval: true }}
        >
            This content was generated by AI.
        </AILabelExplanation>
    );

    it("renders a button trigger when popover content is provided", () => {
        render(<AILabel popover={explanation} />);
        const trigger = screen.getByRole("button");
        expect(trigger).toHaveAttribute("type", "button");
    });

    it("opens the popover on click and closes on Escape", async () => {
        const user = userEvent.setup();
        render(<AILabel popover={explanation} />);

        expect(screen.queryByText("This content was generated by AI.")).not.toBeInTheDocument();

        await user.click(screen.getByRole("button"));
        expect(await screen.findByText("This content was generated by AI.")).toBeInTheDocument();

        await user.keyboard("{Escape}");
        await waitFor(() =>
            expect(screen.queryByText("This content was generated by AI.")).not.toBeInTheDocument(),
        );
    });

    it("opens the popover via keyboard (Enter on the focused trigger)", async () => {
        const user = userEvent.setup();
        render(<AILabel popover={explanation} />);

        await user.tab();
        expect(screen.getByRole("button")).toHaveFocus();

        await user.keyboard("{Enter}");
        expect(await screen.findByText("This content was generated by AI.")).toBeInTheDocument();
    });

    it("renders the provenance sections (confidence method, grounding link, model)", async () => {
        const user = userEvent.setup();
        render(<AILabel popover={explanation} />);
        await user.click(screen.getByRole("button"));

        // Confidence surfaces the *method*, not just the value.
        expect(await screen.findByText("Judged by an LLM")).toBeInTheDocument();
        // Grounding source is a real link.
        expect(screen.getByRole("link", { name: /Source\.pdf/ })).toHaveAttribute("href", "#");
        // Model context.
        expect(screen.getByText("claude-opus-4-8")).toBeInTheDocument();
        expect(screen.getByText("retrieval used")).toBeInTheDocument();
    });

    it("shows the explicit no-sources state when grounding is empty", async () => {
        const user = userEvent.setup();
        render(
            <AILabel
                popover={
                    <AILabelExplanation
                        confidence={{ label: "Unverified", method: "self-reported" }}
                        grounding={[]}
                    />
                }
            />,
        );
        await user.click(screen.getByRole("button"));
        expect(
            await screen.findByText(/No sources — generated without grounding\./),
        ).toBeInTheDocument();
    });
});

describe("AILabel — intent & variant", () => {
    it("defaults to minimal + primary and reflects them on data attributes", () => {
        const { container } = render(<AILabel />);
        const chip = container.querySelector("[data-ai-label]");
        expect(chip).toHaveAttribute("data-variant", "minimal");
        expect(chip).toHaveAttribute("data-intent", "primary");
    });

    it("solid variant uses the filled intent background", () => {
        const { container } = render(<AILabel variant="solid" intent="success" />);
        const chip = container.querySelector("[data-ai-label]");
        expect(chip).toHaveAttribute("data-variant", "solid");
        expect(chip).toHaveAttribute("data-intent", "success");
        expect(chip?.className).toContain("bg-success");
    });

    it("forwards placement (side) to the popover", async () => {
        const user = userEvent.setup();
        render(
            <AILabel
                popover={<AILabelExplanation>Generated by AI.</AILabelExplanation>}
                popoverProps={{ side: "right" }}
            />,
        );
        await user.click(screen.getByRole("button"));
        const panel = await screen.findByText("Generated by AI.");
        // Radix sets data-side on the positioned content wrapper.
        const positioned = panel.closest("[data-side]");
        expect(positioned).toHaveAttribute("data-side", "right");
    });
});
