/**
 * The full glyph map, keyed by `IconName` (@blueprintjs/icons v6.10.0) —
 * GENERATED, do not edit by hand. Regenerate with:  node tools/gen-icons.mjs
 *
 * Importing this module pulls in **every** glyph (≈195 KB), so it is kept in its
 * own file, separate from `index.ts`, and is never imported by `icon.tsx`. Use it
 * for the dynamic string form when you don't care about bundle size:
 *
 *   import { ICON_GLYPHS, registerIcons } from "@/components/ui/icons/all";
 *   registerIcons(ICON_GLYPHS);   // now <… icon="any-name" /> works
 *
 * To tree-shake instead, import individual glyphs from `./index` and pass the
 * object (`<Icon icon={add} />`), or register only the subset you use.
 */
import type { IconGlyph, IconName } from "./index";
import {
    add,
    addApplication,
    addChild,
    addClip,
    addColumnLeft,
    addColumnRight,
    addDerivedColumn,
    addLocation,
    addParent,
    addRowBottom,
    addRowTop,
    addTile,
    addToArtifact,
    addToFolder,
    aimpointsTarget,
    airplane,
    alignCenter,
    alignJustify,
    alignLeft,
    alignRight,
    alignmentBottom,
    alignmentHorizontalCenter,
    alignmentLeft,
    alignmentRight,
    alignmentTop,
    alignmentVerticalCenter,
    ammunition,
    anchor,
    annotation,
    announcement,
    antenna,
    appHeader,
    application,
    applications,
    archive,
    areaOfInterest,
    array,
    arrayBoolean,
    arrayDate,
    arrayFloatingPoint,
    arrayNumeric,
    arrayObject,
    arrayString,
    arrayTimestamp,
    arrowBottomLeft,
    arrowBottomRight,
    arrowDown,
    arrowLeft,
    arrowRight,
    arrowTopLeft,
    arrowTopRight,
    arrowUp,
    arrowsArc,
    arrowsHorizontal,
    arrowsVertical,
    asterisk,
    at,
    automaticUpdates,
    axle,
    backlink,
    backwardTen,
    badge,
    banCircle,
    bankAccount,
    barcode,
    binaryNumber,
    blank,
    blockPromote,
    blockedPerson,
    bold,
    book,
    bookmark,
    box,
    branchLocked,
    branchUnlocked,
    briefcase,
    bringData,
    bringForward,
    britishPound,
    bug,
    buggy,
    build,
    bullseye,
    calculator,
    calendar,
    camera,
    caretDown,
    caretLeft,
    caretRight,
    caretUp,
    cargoShip,
    cellTower,
    changes,
    chart,
    chat,
    chevronBackward,
    chevronDown,
    chevronForward,
    chevronLeft,
    chevronRight,
    chevronUp,
    circle,
    circleArrowDown,
    circleArrowLeft,
    circleArrowRight,
    circleArrowUp,
    circleDashed,
    citation,
    clean,
    clip,
    clipboard,
    clipboardFile,
    cloud,
    cloudDownload,
    cloudServer,
    cloudTick,
    cloudUpload,
    code,
    codeBlock,
    cog,
    collapseAll,
    colorFill,
    columnLayout,
    comment,
    comparison,
    compass,
    compressed,
    confirm,
    console,
    consoleAlert,
    construction,
    contrast,
    control,
    creditCard,
    crop,
    cross,
    crossCircle,
    crown,
    crystalBall,
    cssStyle,
    cube,
    cubeAdd,
    cubeCutout,
    cubeCutouts,
    cubeEdit,
    cubeRemove,
    cubes,
    curlyBraces,
    curvedRangeChart,
    cut,
    cycle,
    dashboard,
    dataCloud,
    dataConnection,
    dataLineage,
    dataSearch,
    dataSync,
    database,
    deleteIcon,
    deleteClip,
    delta,
    deriveColumn,
    descendant,
    desktop,
    detection,
    diagnosis,
    diagramTree,
    directionLeft,
    directionRight,
    disable,
    divide,
    document,
    documentCode,
    documentLocked,
    documentOpen,
    documentShare,
    dollar,
    dot,
    doubleCaretHorizontal,
    doubleCaretVertical,
    doubleChevronDown,
    doubleChevronLeft,
    doubleChevronRight,
    doubleChevronUp,
    doughnutChart,
    download,
    dragHandleHorizontal,
    dragHandleVertical,
    draw,
    drawerLeft,
    drawerLeftFilled,
    drawerRight,
    drawerRightFilled,
    driveTime,
    drone,
    droneUav,
    duplicate,
    edit,
    eject,
    emoji,
    endnote,
    endorsed,
    engagement,
    envelope,
    equals,
    eraser,
    error,
    euro,
    excavator,
    exchange,
    excludeRow,
    expandAll,
    explain,
    exportIcon,
    eyeOff,
    eyeOn,
    eyeOpen,
    fastBackward,
    fastForward,
    feed,
    feedSubscribed,
    fighterJet,
    film,
    filter,
    filterKeep,
    filterList,
    filterOpen,
    filterRemove,
    filterSortAsc,
    filterSortDesc,
    flag,
    flame,
    flash,
    floatingPoint,
    floppyDisk,
    flowBranch,
    flowEnd,
    flowLinear,
    flowReview,
    flowReviewBranch,
    flows,
    folderClose,
    folderNew,
    folderOpen,
    folderShared,
    folderSharedOpen,
    follower,
    following,
    font,
    fork,
    forkEnd,
    form,
    forwardTen,
    frameToFrame,
    fuel,
    fullCircle,
    fullStackedChart,
    fullscreen,
    functionIcon,
    functionMinimal,
    ganttChart,
    generate,
    geofence,
    geolocation,
    geosearch,
    geotime,
    giftBox,
    gitBranch,
    gitCommit,
    gitMerge,
    gitNewBranch,
    gitPull,
    gitPush,
    gitRebase,
    gitRepo,
    glass,
    globe,
    globeNetwork,
    globeNetworkAdd,
    graph,
    graphRemove,
    greaterThan,
    greaterThanOrEqualTo,
    grid,
    gridView,
    groupItem,
    groupObjects,
    groupedBarChart,
    hand,
    handDown,
    handLeft,
    handRight,
    handUp,
    hat,
    header,
    headerOne,
    headerThree,
    headerTwo,
    headset,
    heart,
    heartBroken,
    heatGrid,
    heatmap,
    helicopter,
    help,
    helperManagement,
    hexagon,
    highPriority,
    highVoltagePole,
    highlight,
    history,
    home,
    horizontalBarChart,
    horizontalBarChartAsc,
    horizontalBarChartDesc,
    horizontalDistribution,
    horizontalInbetween,
    hurricane,
    idNumber,
    imageRotateLeft,
    imageRotateRight,
    importIcon,
    inbox,
    inboxFiltered,
    inboxGeo,
    inboxSearch,
    inboxUpdate,
    infoSign,
    inheritance,
    inheritedGroup,
    innerJoin,
    input,
    insert,
    intelligence,
    intersection,
    ipAddress,
    issue,
    issueClosed,
    issueNew,
    italic,
    joinTable,
    key,
    keyBackspace,
    keyCommand,
    keyControl,
    keyDelete,
    keyEnter,
    keyEscape,
    keyOption,
    keyShift,
    keyTab,
    knownVehicle,
    labTest,
    label,
    layer,
    layerOutline,
    layers,
    layout,
    layoutAuto,
    layoutBalloon,
    layoutBottomRowThreeTiles,
    layoutBottomRowTwoTiles,
    layoutCircle,
    layoutGrid,
    layoutGroupBy,
    layoutHierarchy,
    layoutLeftColumnThreeTiles,
    layoutLeftColumnTwoTiles,
    layoutLinear,
    layoutRightColumnThreeTiles,
    layoutRightColumnTwoTiles,
    layoutSkewGrid,
    layoutSortedClusters,
    layoutThreeColumns,
    layoutThreeRows,
    layoutTopRowThreeTiles,
    layoutTopRowTwoTiles,
    layoutTwoColumns,
    layoutTwoRows,
    learning,
    leftJoin,
    lengthenText,
    lessThan,
    lessThanOrEqualTo,
    lifesaver,
    lightbulb,
    lightning,
    link,
    linkedSquares,
    list,
    listColumns,
    listDetailView,
    locate,
    lock,
    locomotive,
    logIn,
    logOut,
    lowVoltagePole,
    manual,
    manuallyEnteredData,
    manyToMany,
    manyToOne,
    map,
    mapCreate,
    mapMarker,
    markdown,
    maximize,
    media,
    menu,
    menuClosed,
    menuOpen,
    mergeColumns,
    mergeLinks,
    microphone,
    minimize,
    minus,
    mobilePhone,
    mobileVideo,
    modal,
    modalFilled,
    model,
    moon,
    more,
    mountain,
    move,
    mugshot,
    multiSelect,
    music,
    nest,
    newComment,
    newDrawing,
    newGridItem,
    newLayer,
    newLayers,
    newLink,
    newObject,
    newPerson,
    newPrescription,
    newShield,
    newTextBox,
    ninja,
    notEqualTo,
    notifications,
    notificationsAdd,
    notificationsSnooze,
    notificationsUpdated,
    numberedList,
    numerical,
    objectView,
    office,
    offline,
    oilField,
    oneColumn,
    oneToMany,
    oneToOne,
    openApplication,
    outdated,
    outerJoin,
    output,
    packageIcon,
    pageBreak,
    pageLayout,
    panel,
    panelStats,
    panelTable,
    paperclip,
    paragraph,
    pasteVariable,
    path,
    pathSearch,
    pause,
    people,
    percentage,
    person,
    phone,
    phoneCall,
    phoneForward,
    phoneSearch,
    pieChart,
    pill,
    pin,
    pistol,
    pivot,
    pivotTable,
    play,
    playbook,
    plus,
    polygonFilter,
    popout,
    power,
    predictiveAnalysis,
    prescription,
    presentation,
    print,
    projects,
    properties,
    property,
    publishFunction,
    pulse,
    rain,
    random,
    rangeRing,
    record,
    rectHeight,
    rectWidth,
    rectangle,
    redo,
    refresh,
    refreshOff,
    regex,
    regressionChart,
    remove,
    removeColumn,
    removeColumnLeft,
    removeColumnRight,
    removeRowBottom,
    removeRowTop,
    repeat,
    reset,
    resolve,
    rig,
    rightJoin,
    ring,
    rocket,
    rocketSlant,
    rootFolder,
    rotateCcw,
    rotateCw,
    rotateDocument,
    rotatePage,
    route,
    runHistory,
    satellite,
    saved,
    scatterPlot,
    search,
    searchAround,
    searchTemplate,
    searchText,
    segmentedControl,
    select,
    selection,
    selectionBox,
    selectionBoxAdd,
    selectionBoxEdit,
    selectionBoxRemove,
    sendBackward,
    sendMessage,
    sendTo,
    sendToGraph,
    sendToMap,
    sensor,
    seriesAdd,
    seriesConfiguration,
    seriesDerived,
    seriesFiltered,
    seriesSearch,
    server,
    serverInstall,
    settings,
    shapes,
    share,
    sharedFilter,
    shield,
    ship,
    shop,
    shoppingCart,
    shortenText,
    signalSearch,
    simCard,
    slash,
    smallCross,
    smallInfoSign,
    smallMinus,
    smallPlus,
    smallSquare,
    smallTick,
    snowflake,
    soccerBall,
    socialMedia,
    sort,
    sortAlphabetical,
    sortAlphabeticalDesc,
    sortAsc,
    sortDesc,
    sortNumerical,
    sortNumericalDesc,
    spellCheck,
    spin,
    splitColumns,
    sportsStadium,
    square,
    stackedChart,
    stadiumGeometry,
    star,
    starEmpty,
    stepBackward,
    stepChart,
    stepForward,
    stop,
    stopwatch,
    strikethrough,
    style,
    subscript,
    subtractRightJoin,
    superscript,
    swapHorizontal,
    swapVertical,
    sweep,
    switchIcon,
    symbolCircle,
    symbolCross,
    symbolDiamond,
    symbolRectangle,
    symbolSquare,
    symbolTriangleDown,
    symbolTriangleUp,
    syringe,
    tableSync,
    tag,
    tagAdd,
    tagPromote,
    tagRefresh,
    tagUndo,
    tags,
    takeAction,
    tank,
    target,
    taxi,
    team,
    temperature,
    textHighlight,
    th,
    thAdd,
    thDerived,
    thDisconnect,
    thFiltered,
    thList,
    thListAdd,
    thVirtual,
    thVirtualAdd,
    thirdParty,
    thumbsDown,
    thumbsUp,
    tick,
    tickCircle,
    time,
    timelineAreaChart,
    timelineBarChart,
    timelineEvents,
    timelineLineChart,
    tint,
    torch,
    tractor,
    train,
    translate,
    trash,
    tree,
    trendingDown,
    trendingUp,
    trophy,
    truck,
    twoColumns,
    unarchive,
    underline,
    undo,
    ungroupObjects,
    unknownVehicle,
    unlink,
    unlock,
    unpin,
    unresolve,
    updated,
    upload,
    user,
    variable,
    variableLayer,
    vector,
    verticalBarChartAsc,
    verticalBarChartDesc,
    verticalDistribution,
    verticalInbetween,
    video,
    virus,
    volumeDown,
    volumeOff,
    volumeUp,
    walk,
    warningSign,
    waterfallChart,
    waves,
    widget,
    widgetButton,
    widgetFooter,
    widgetHeader,
    wind,
    won,
    wrapLines,
    wrench,
    wrenchRedo,
    wrenchSnooze,
    wrenchTime,
    yen,
    zoomIn,
    zoomOut,
    zoomToFit,
} from "./index";

export { registerIcons, getRegisteredGlyph } from "./registry";

export const ICON_GLYPHS: Record<IconName, IconGlyph> = {
    "add": add,
    "add-application": addApplication,
    "add-child": addChild,
    "add-clip": addClip,
    "add-column-left": addColumnLeft,
    "add-column-right": addColumnRight,
    "add-derived-column": addDerivedColumn,
    "add-location": addLocation,
    "add-parent": addParent,
    "add-row-bottom": addRowBottom,
    "add-row-top": addRowTop,
    "add-tile": addTile,
    "add-to-artifact": addToArtifact,
    "add-to-folder": addToFolder,
    "aimpoints-target": aimpointsTarget,
    "airplane": airplane,
    "align-center": alignCenter,
    "align-justify": alignJustify,
    "align-left": alignLeft,
    "align-right": alignRight,
    "alignment-bottom": alignmentBottom,
    "alignment-horizontal-center": alignmentHorizontalCenter,
    "alignment-left": alignmentLeft,
    "alignment-right": alignmentRight,
    "alignment-top": alignmentTop,
    "alignment-vertical-center": alignmentVerticalCenter,
    "ammunition": ammunition,
    "anchor": anchor,
    "annotation": annotation,
    "announcement": announcement,
    "antenna": antenna,
    "app-header": appHeader,
    "application": application,
    "applications": applications,
    "archive": archive,
    "area-of-interest": areaOfInterest,
    "array": array,
    "array-boolean": arrayBoolean,
    "array-date": arrayDate,
    "array-floating-point": arrayFloatingPoint,
    "array-numeric": arrayNumeric,
    "array-object": arrayObject,
    "array-string": arrayString,
    "array-timestamp": arrayTimestamp,
    "arrow-bottom-left": arrowBottomLeft,
    "arrow-bottom-right": arrowBottomRight,
    "arrow-down": arrowDown,
    "arrow-left": arrowLeft,
    "arrow-right": arrowRight,
    "arrow-top-left": arrowTopLeft,
    "arrow-top-right": arrowTopRight,
    "arrow-up": arrowUp,
    "arrows-arc": arrowsArc,
    "arrows-horizontal": arrowsHorizontal,
    "arrows-vertical": arrowsVertical,
    "asterisk": asterisk,
    "at": at,
    "automatic-updates": automaticUpdates,
    "axle": axle,
    "backlink": backlink,
    "backward-ten": backwardTen,
    "badge": badge,
    "ban-circle": banCircle,
    "bank-account": bankAccount,
    "barcode": barcode,
    "binary-number": binaryNumber,
    "blank": blank,
    "block-promote": blockPromote,
    "blocked-person": blockedPerson,
    "bold": bold,
    "book": book,
    "bookmark": bookmark,
    "box": box,
    "branch-locked": branchLocked,
    "branch-unlocked": branchUnlocked,
    "briefcase": briefcase,
    "bring-data": bringData,
    "bring-forward": bringForward,
    "british-pound": britishPound,
    "bug": bug,
    "buggy": buggy,
    "build": build,
    "bullseye": bullseye,
    "calculator": calculator,
    "calendar": calendar,
    "camera": camera,
    "caret-down": caretDown,
    "caret-left": caretLeft,
    "caret-right": caretRight,
    "caret-up": caretUp,
    "cargo-ship": cargoShip,
    "cell-tower": cellTower,
    "changes": changes,
    "chart": chart,
    "chat": chat,
    "chevron-backward": chevronBackward,
    "chevron-down": chevronDown,
    "chevron-forward": chevronForward,
    "chevron-left": chevronLeft,
    "chevron-right": chevronRight,
    "chevron-up": chevronUp,
    "circle": circle,
    "circle-arrow-down": circleArrowDown,
    "circle-arrow-left": circleArrowLeft,
    "circle-arrow-right": circleArrowRight,
    "circle-arrow-up": circleArrowUp,
    "circle-dashed": circleDashed,
    "citation": citation,
    "clean": clean,
    "clip": clip,
    "clipboard": clipboard,
    "clipboard-file": clipboardFile,
    "cloud": cloud,
    "cloud-download": cloudDownload,
    "cloud-server": cloudServer,
    "cloud-tick": cloudTick,
    "cloud-upload": cloudUpload,
    "code": code,
    "code-block": codeBlock,
    "cog": cog,
    "collapse-all": collapseAll,
    "color-fill": colorFill,
    "column-layout": columnLayout,
    "comment": comment,
    "comparison": comparison,
    "compass": compass,
    "compressed": compressed,
    "confirm": confirm,
    "console": console,
    "console-alert": consoleAlert,
    "construction": construction,
    "contrast": contrast,
    "control": control,
    "credit-card": creditCard,
    "crop": crop,
    "cross": cross,
    "cross-circle": crossCircle,
    "crown": crown,
    "crystal-ball": crystalBall,
    "css-style": cssStyle,
    "cube": cube,
    "cube-add": cubeAdd,
    "cube-cutout": cubeCutout,
    "cube-cutouts": cubeCutouts,
    "cube-edit": cubeEdit,
    "cube-remove": cubeRemove,
    "cubes": cubes,
    "curly-braces": curlyBraces,
    "curved-range-chart": curvedRangeChart,
    "cut": cut,
    "cycle": cycle,
    "dashboard": dashboard,
    "data-cloud": dataCloud,
    "data-connection": dataConnection,
    "data-lineage": dataLineage,
    "data-search": dataSearch,
    "data-sync": dataSync,
    "database": database,
    "delete": deleteIcon,
    "delete-clip": deleteClip,
    "delta": delta,
    "derive-column": deriveColumn,
    "descendant": descendant,
    "desktop": desktop,
    "detection": detection,
    "diagnosis": diagnosis,
    "diagram-tree": diagramTree,
    "direction-left": directionLeft,
    "direction-right": directionRight,
    "disable": disable,
    "divide": divide,
    "document": document,
    "document-code": documentCode,
    "document-locked": documentLocked,
    "document-open": documentOpen,
    "document-share": documentShare,
    "dollar": dollar,
    "dot": dot,
    "double-caret-horizontal": doubleCaretHorizontal,
    "double-caret-vertical": doubleCaretVertical,
    "double-chevron-down": doubleChevronDown,
    "double-chevron-left": doubleChevronLeft,
    "double-chevron-right": doubleChevronRight,
    "double-chevron-up": doubleChevronUp,
    "doughnut-chart": doughnutChart,
    "download": download,
    "drag-handle-horizontal": dragHandleHorizontal,
    "drag-handle-vertical": dragHandleVertical,
    "draw": draw,
    "drawer-left": drawerLeft,
    "drawer-left-filled": drawerLeftFilled,
    "drawer-right": drawerRight,
    "drawer-right-filled": drawerRightFilled,
    "drive-time": driveTime,
    "drone": drone,
    "drone-uav": droneUav,
    "duplicate": duplicate,
    "edit": edit,
    "eject": eject,
    "emoji": emoji,
    "endnote": endnote,
    "endorsed": endorsed,
    "engagement": engagement,
    "envelope": envelope,
    "equals": equals,
    "eraser": eraser,
    "error": error,
    "euro": euro,
    "excavator": excavator,
    "exchange": exchange,
    "exclude-row": excludeRow,
    "expand-all": expandAll,
    "explain": explain,
    "export": exportIcon,
    "eye-off": eyeOff,
    "eye-on": eyeOn,
    "eye-open": eyeOpen,
    "fast-backward": fastBackward,
    "fast-forward": fastForward,
    "feed": feed,
    "feed-subscribed": feedSubscribed,
    "fighter-jet": fighterJet,
    "film": film,
    "filter": filter,
    "filter-keep": filterKeep,
    "filter-list": filterList,
    "filter-open": filterOpen,
    "filter-remove": filterRemove,
    "filter-sort-asc": filterSortAsc,
    "filter-sort-desc": filterSortDesc,
    "flag": flag,
    "flame": flame,
    "flash": flash,
    "floating-point": floatingPoint,
    "floppy-disk": floppyDisk,
    "flow-branch": flowBranch,
    "flow-end": flowEnd,
    "flow-linear": flowLinear,
    "flow-review": flowReview,
    "flow-review-branch": flowReviewBranch,
    "flows": flows,
    "folder-close": folderClose,
    "folder-new": folderNew,
    "folder-open": folderOpen,
    "folder-shared": folderShared,
    "folder-shared-open": folderSharedOpen,
    "follower": follower,
    "following": following,
    "font": font,
    "fork": fork,
    "fork-end": forkEnd,
    "form": form,
    "forward-ten": forwardTen,
    "frame-to-frame": frameToFrame,
    "fuel": fuel,
    "full-circle": fullCircle,
    "full-stacked-chart": fullStackedChart,
    "fullscreen": fullscreen,
    "function": functionIcon,
    "function-minimal": functionMinimal,
    "gantt-chart": ganttChart,
    "generate": generate,
    "geofence": geofence,
    "geolocation": geolocation,
    "geosearch": geosearch,
    "geotime": geotime,
    "gift-box": giftBox,
    "git-branch": gitBranch,
    "git-commit": gitCommit,
    "git-merge": gitMerge,
    "git-new-branch": gitNewBranch,
    "git-pull": gitPull,
    "git-push": gitPush,
    "git-rebase": gitRebase,
    "git-repo": gitRepo,
    "glass": glass,
    "globe": globe,
    "globe-network": globeNetwork,
    "globe-network-add": globeNetworkAdd,
    "graph": graph,
    "graph-remove": graphRemove,
    "greater-than": greaterThan,
    "greater-than-or-equal-to": greaterThanOrEqualTo,
    "grid": grid,
    "grid-view": gridView,
    "group-item": groupItem,
    "group-objects": groupObjects,
    "grouped-bar-chart": groupedBarChart,
    "hand": hand,
    "hand-down": handDown,
    "hand-left": handLeft,
    "hand-right": handRight,
    "hand-up": handUp,
    "hat": hat,
    "header": header,
    "header-one": headerOne,
    "header-three": headerThree,
    "header-two": headerTwo,
    "headset": headset,
    "heart": heart,
    "heart-broken": heartBroken,
    "heat-grid": heatGrid,
    "heatmap": heatmap,
    "helicopter": helicopter,
    "help": help,
    "helper-management": helperManagement,
    "hexagon": hexagon,
    "high-priority": highPriority,
    "high-voltage-pole": highVoltagePole,
    "highlight": highlight,
    "history": history,
    "home": home,
    "horizontal-bar-chart": horizontalBarChart,
    "horizontal-bar-chart-asc": horizontalBarChartAsc,
    "horizontal-bar-chart-desc": horizontalBarChartDesc,
    "horizontal-distribution": horizontalDistribution,
    "horizontal-inbetween": horizontalInbetween,
    "hurricane": hurricane,
    "id-number": idNumber,
    "image-rotate-left": imageRotateLeft,
    "image-rotate-right": imageRotateRight,
    "import": importIcon,
    "inbox": inbox,
    "inbox-filtered": inboxFiltered,
    "inbox-geo": inboxGeo,
    "inbox-search": inboxSearch,
    "inbox-update": inboxUpdate,
    "info-sign": infoSign,
    "inheritance": inheritance,
    "inherited-group": inheritedGroup,
    "inner-join": innerJoin,
    "input": input,
    "insert": insert,
    "intelligence": intelligence,
    "intersection": intersection,
    "ip-address": ipAddress,
    "issue": issue,
    "issue-closed": issueClosed,
    "issue-new": issueNew,
    "italic": italic,
    "join-table": joinTable,
    "key": key,
    "key-backspace": keyBackspace,
    "key-command": keyCommand,
    "key-control": keyControl,
    "key-delete": keyDelete,
    "key-enter": keyEnter,
    "key-escape": keyEscape,
    "key-option": keyOption,
    "key-shift": keyShift,
    "key-tab": keyTab,
    "known-vehicle": knownVehicle,
    "lab-test": labTest,
    "label": label,
    "layer": layer,
    "layer-outline": layerOutline,
    "layers": layers,
    "layout": layout,
    "layout-auto": layoutAuto,
    "layout-balloon": layoutBalloon,
    "layout-bottom-row-three-tiles": layoutBottomRowThreeTiles,
    "layout-bottom-row-two-tiles": layoutBottomRowTwoTiles,
    "layout-circle": layoutCircle,
    "layout-grid": layoutGrid,
    "layout-group-by": layoutGroupBy,
    "layout-hierarchy": layoutHierarchy,
    "layout-left-column-three-tiles": layoutLeftColumnThreeTiles,
    "layout-left-column-two-tiles": layoutLeftColumnTwoTiles,
    "layout-linear": layoutLinear,
    "layout-right-column-three-tiles": layoutRightColumnThreeTiles,
    "layout-right-column-two-tiles": layoutRightColumnTwoTiles,
    "layout-skew-grid": layoutSkewGrid,
    "layout-sorted-clusters": layoutSortedClusters,
    "layout-three-columns": layoutThreeColumns,
    "layout-three-rows": layoutThreeRows,
    "layout-top-row-three-tiles": layoutTopRowThreeTiles,
    "layout-top-row-two-tiles": layoutTopRowTwoTiles,
    "layout-two-columns": layoutTwoColumns,
    "layout-two-rows": layoutTwoRows,
    "learning": learning,
    "left-join": leftJoin,
    "lengthen-text": lengthenText,
    "less-than": lessThan,
    "less-than-or-equal-to": lessThanOrEqualTo,
    "lifesaver": lifesaver,
    "lightbulb": lightbulb,
    "lightning": lightning,
    "link": link,
    "linked-squares": linkedSquares,
    "list": list,
    "list-columns": listColumns,
    "list-detail-view": listDetailView,
    "locate": locate,
    "lock": lock,
    "locomotive": locomotive,
    "log-in": logIn,
    "log-out": logOut,
    "low-voltage-pole": lowVoltagePole,
    "manual": manual,
    "manually-entered-data": manuallyEnteredData,
    "many-to-many": manyToMany,
    "many-to-one": manyToOne,
    "map": map,
    "map-create": mapCreate,
    "map-marker": mapMarker,
    "markdown": markdown,
    "maximize": maximize,
    "media": media,
    "menu": menu,
    "menu-closed": menuClosed,
    "menu-open": menuOpen,
    "merge-columns": mergeColumns,
    "merge-links": mergeLinks,
    "microphone": microphone,
    "minimize": minimize,
    "minus": minus,
    "mobile-phone": mobilePhone,
    "mobile-video": mobileVideo,
    "modal": modal,
    "modal-filled": modalFilled,
    "model": model,
    "moon": moon,
    "more": more,
    "mountain": mountain,
    "move": move,
    "mugshot": mugshot,
    "multi-select": multiSelect,
    "music": music,
    "nest": nest,
    "new-comment": newComment,
    "new-drawing": newDrawing,
    "new-grid-item": newGridItem,
    "new-layer": newLayer,
    "new-layers": newLayers,
    "new-link": newLink,
    "new-object": newObject,
    "new-person": newPerson,
    "new-prescription": newPrescription,
    "new-shield": newShield,
    "new-text-box": newTextBox,
    "ninja": ninja,
    "not-equal-to": notEqualTo,
    "notifications": notifications,
    "notifications-add": notificationsAdd,
    "notifications-snooze": notificationsSnooze,
    "notifications-updated": notificationsUpdated,
    "numbered-list": numberedList,
    "numerical": numerical,
    "object-view": objectView,
    "office": office,
    "offline": offline,
    "oil-field": oilField,
    "one-column": oneColumn,
    "one-to-many": oneToMany,
    "one-to-one": oneToOne,
    "open-application": openApplication,
    "outdated": outdated,
    "outer-join": outerJoin,
    "output": output,
    "package": packageIcon,
    "page-break": pageBreak,
    "page-layout": pageLayout,
    "panel": panel,
    "panel-stats": panelStats,
    "panel-table": panelTable,
    "paperclip": paperclip,
    "paragraph": paragraph,
    "paste-variable": pasteVariable,
    "path": path,
    "path-search": pathSearch,
    "pause": pause,
    "people": people,
    "percentage": percentage,
    "person": person,
    "phone": phone,
    "phone-call": phoneCall,
    "phone-forward": phoneForward,
    "phone-search": phoneSearch,
    "pie-chart": pieChart,
    "pill": pill,
    "pin": pin,
    "pistol": pistol,
    "pivot": pivot,
    "pivot-table": pivotTable,
    "play": play,
    "playbook": playbook,
    "plus": plus,
    "polygon-filter": polygonFilter,
    "popout": popout,
    "power": power,
    "predictive-analysis": predictiveAnalysis,
    "prescription": prescription,
    "presentation": presentation,
    "print": print,
    "projects": projects,
    "properties": properties,
    "property": property,
    "publish-function": publishFunction,
    "pulse": pulse,
    "rain": rain,
    "random": random,
    "range-ring": rangeRing,
    "record": record,
    "rect-height": rectHeight,
    "rect-width": rectWidth,
    "rectangle": rectangle,
    "redo": redo,
    "refresh": refresh,
    "refresh-off": refreshOff,
    "regex": regex,
    "regression-chart": regressionChart,
    "remove": remove,
    "remove-column": removeColumn,
    "remove-column-left": removeColumnLeft,
    "remove-column-right": removeColumnRight,
    "remove-row-bottom": removeRowBottom,
    "remove-row-top": removeRowTop,
    "repeat": repeat,
    "reset": reset,
    "resolve": resolve,
    "rig": rig,
    "right-join": rightJoin,
    "ring": ring,
    "rocket": rocket,
    "rocket-slant": rocketSlant,
    "root-folder": rootFolder,
    "rotate-ccw": rotateCcw,
    "rotate-cw": rotateCw,
    "rotate-document": rotateDocument,
    "rotate-page": rotatePage,
    "route": route,
    "run-history": runHistory,
    "satellite": satellite,
    "saved": saved,
    "scatter-plot": scatterPlot,
    "search": search,
    "search-around": searchAround,
    "search-template": searchTemplate,
    "search-text": searchText,
    "segmented-control": segmentedControl,
    "select": select,
    "selection": selection,
    "selection-box": selectionBox,
    "selection-box-add": selectionBoxAdd,
    "selection-box-edit": selectionBoxEdit,
    "selection-box-remove": selectionBoxRemove,
    "send-backward": sendBackward,
    "send-message": sendMessage,
    "send-to": sendTo,
    "send-to-graph": sendToGraph,
    "send-to-map": sendToMap,
    "sensor": sensor,
    "series-add": seriesAdd,
    "series-configuration": seriesConfiguration,
    "series-derived": seriesDerived,
    "series-filtered": seriesFiltered,
    "series-search": seriesSearch,
    "server": server,
    "server-install": serverInstall,
    "settings": settings,
    "shapes": shapes,
    "share": share,
    "shared-filter": sharedFilter,
    "shield": shield,
    "ship": ship,
    "shop": shop,
    "shopping-cart": shoppingCart,
    "shorten-text": shortenText,
    "signal-search": signalSearch,
    "sim-card": simCard,
    "slash": slash,
    "small-cross": smallCross,
    "small-info-sign": smallInfoSign,
    "small-minus": smallMinus,
    "small-plus": smallPlus,
    "small-square": smallSquare,
    "small-tick": smallTick,
    "snowflake": snowflake,
    "soccer-ball": soccerBall,
    "social-media": socialMedia,
    "sort": sort,
    "sort-alphabetical": sortAlphabetical,
    "sort-alphabetical-desc": sortAlphabeticalDesc,
    "sort-asc": sortAsc,
    "sort-desc": sortDesc,
    "sort-numerical": sortNumerical,
    "sort-numerical-desc": sortNumericalDesc,
    "spell-check": spellCheck,
    "spin": spin,
    "split-columns": splitColumns,
    "sports-stadium": sportsStadium,
    "square": square,
    "stacked-chart": stackedChart,
    "stadium-geometry": stadiumGeometry,
    "star": star,
    "star-empty": starEmpty,
    "step-backward": stepBackward,
    "step-chart": stepChart,
    "step-forward": stepForward,
    "stop": stop,
    "stopwatch": stopwatch,
    "strikethrough": strikethrough,
    "style": style,
    "subscript": subscript,
    "subtract-right-join": subtractRightJoin,
    "superscript": superscript,
    "swap-horizontal": swapHorizontal,
    "swap-vertical": swapVertical,
    "sweep": sweep,
    "switch": switchIcon,
    "symbol-circle": symbolCircle,
    "symbol-cross": symbolCross,
    "symbol-diamond": symbolDiamond,
    "symbol-rectangle": symbolRectangle,
    "symbol-square": symbolSquare,
    "symbol-triangle-down": symbolTriangleDown,
    "symbol-triangle-up": symbolTriangleUp,
    "syringe": syringe,
    "table-sync": tableSync,
    "tag": tag,
    "tag-add": tagAdd,
    "tag-promote": tagPromote,
    "tag-refresh": tagRefresh,
    "tag-undo": tagUndo,
    "tags": tags,
    "take-action": takeAction,
    "tank": tank,
    "target": target,
    "taxi": taxi,
    "team": team,
    "temperature": temperature,
    "text-highlight": textHighlight,
    "th": th,
    "th-add": thAdd,
    "th-derived": thDerived,
    "th-disconnect": thDisconnect,
    "th-filtered": thFiltered,
    "th-list": thList,
    "th-list-add": thListAdd,
    "th-virtual": thVirtual,
    "th-virtual-add": thVirtualAdd,
    "third-party": thirdParty,
    "thumbs-down": thumbsDown,
    "thumbs-up": thumbsUp,
    "tick": tick,
    "tick-circle": tickCircle,
    "time": time,
    "timeline-area-chart": timelineAreaChart,
    "timeline-bar-chart": timelineBarChart,
    "timeline-events": timelineEvents,
    "timeline-line-chart": timelineLineChart,
    "tint": tint,
    "torch": torch,
    "tractor": tractor,
    "train": train,
    "translate": translate,
    "trash": trash,
    "tree": tree,
    "trending-down": trendingDown,
    "trending-up": trendingUp,
    "trophy": trophy,
    "truck": truck,
    "two-columns": twoColumns,
    "unarchive": unarchive,
    "underline": underline,
    "undo": undo,
    "ungroup-objects": ungroupObjects,
    "unknown-vehicle": unknownVehicle,
    "unlink": unlink,
    "unlock": unlock,
    "unpin": unpin,
    "unresolve": unresolve,
    "updated": updated,
    "upload": upload,
    "user": user,
    "variable": variable,
    "variable-layer": variableLayer,
    "vector": vector,
    "vertical-bar-chart-asc": verticalBarChartAsc,
    "vertical-bar-chart-desc": verticalBarChartDesc,
    "vertical-distribution": verticalDistribution,
    "vertical-inbetween": verticalInbetween,
    "video": video,
    "virus": virus,
    "volume-down": volumeDown,
    "volume-off": volumeOff,
    "volume-up": volumeUp,
    "walk": walk,
    "warning-sign": warningSign,
    "waterfall-chart": waterfallChart,
    "waves": waves,
    "widget": widget,
    "widget-button": widgetButton,
    "widget-footer": widgetFooter,
    "widget-header": widgetHeader,
    "wind": wind,
    "won": won,
    "wrap-lines": wrapLines,
    "wrench": wrench,
    "wrench-redo": wrenchRedo,
    "wrench-snooze": wrenchSnooze,
    "wrench-time": wrenchTime,
    "yen": yen,
    "zoom-in": zoomIn,
    "zoom-out": zoomOut,
    "zoom-to-fit": zoomToFit,
};
