// AUTO-GENERATED by tools/gen-component-meta.mjs — do not edit by hand.
// Re-run after adding components or tests:  pnpm gen:meta

/** Per-component metadata surfaced as badges on the showcase overview tiles. */
export interface ComponentMeta {
    /** Test cases in the component's suite, bucketed by title-keyword heuristic. */
    tests: { total: number; a11y: number; keyboard: number; behavior: number };
    /** Server-renderable (no `"use client"` directive). */
    rsc: boolean;
    /** Renders into a portal — needs `dark` threading (see the overlays recipe). */
    portal: boolean;
    /** Backed by a `@radix-ui/*` headless primitive. */
    radix: boolean;
    /** Exposes `asChild` (Radix Slot polymorphism). */
    polymorphic: boolean;
    /** Distributable as owned-source via registry.json. */
    registry: boolean;
}

export const COMPONENT_META: Record<string, ComponentMeta> = {
    "alert": {
        "tests": {
            "total": 2,
            "a11y": 1,
            "keyboard": 0,
            "behavior": 1
        },
        "rsc": false,
        "portal": true,
        "radix": true,
        "polymorphic": false,
        "registry": true
    },
    "anchor-button": {
        "tests": {
            "total": 13,
            "a11y": 4,
            "keyboard": 1,
            "behavior": 8
        },
        "rsc": false,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true
    },
    "breadcrumbs": {
        "tests": {
            "total": 0,
            "a11y": 0,
            "keyboard": 0,
            "behavior": 0
        },
        "rsc": false,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true
    },
    "button": {
        "tests": {
            "total": 0,
            "a11y": 0,
            "keyboard": 0,
            "behavior": 0
        },
        "rsc": false,
        "portal": false,
        "radix": true,
        "polymorphic": true,
        "registry": true
    },
    "button-group": {
        "tests": {
            "total": 9,
            "a11y": 1,
            "keyboard": 0,
            "behavior": 8
        },
        "rsc": false,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true
    },
    "callout": {
        "tests": {
            "total": 0,
            "a11y": 0,
            "keyboard": 0,
            "behavior": 0
        },
        "rsc": true,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true
    },
    "card": {
        "tests": {
            "total": 0,
            "a11y": 0,
            "keyboard": 0,
            "behavior": 0
        },
        "rsc": true,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true
    },
    "card-list": {
        "tests": {
            "total": 0,
            "a11y": 0,
            "keyboard": 0,
            "behavior": 0
        },
        "rsc": true,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true
    },
    "checkbox": {
        "tests": {
            "total": 0,
            "a11y": 0,
            "keyboard": 0,
            "behavior": 0
        },
        "rsc": false,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true
    },
    "collapse": {
        "tests": {
            "total": 0,
            "a11y": 0,
            "keyboard": 0,
            "behavior": 0
        },
        "rsc": false,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true
    },
    "context-menu": {
        "tests": {
            "total": 3,
            "a11y": 1,
            "keyboard": 2,
            "behavior": 0
        },
        "rsc": false,
        "portal": true,
        "radix": true,
        "polymorphic": true,
        "registry": true
    },
    "control-base": {
        "tests": {
            "total": 0,
            "a11y": 0,
            "keyboard": 0,
            "behavior": 0
        },
        "rsc": true,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true
    },
    "control-card": {
        "tests": {
            "total": 0,
            "a11y": 0,
            "keyboard": 0,
            "behavior": 0
        },
        "rsc": false,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true
    },
    "control-group": {
        "tests": {
            "total": 12,
            "a11y": 1,
            "keyboard": 0,
            "behavior": 11
        },
        "rsc": true,
        "portal": false,
        "radix": false,
        "polymorphic": true,
        "registry": true
    },
    "data-table": {
        "tests": {
            "total": 76,
            "a11y": 3,
            "keyboard": 11,
            "behavior": 62
        },
        "rsc": false,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true
    },
    "date-input": {
        "tests": {
            "total": 0,
            "a11y": 0,
            "keyboard": 0,
            "behavior": 0
        },
        "rsc": false,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true
    },
    "date-picker": {
        "tests": {
            "total": 0,
            "a11y": 0,
            "keyboard": 0,
            "behavior": 0
        },
        "rsc": false,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true
    },
    "date-range-input": {
        "tests": {
            "total": 8,
            "a11y": 2,
            "keyboard": 0,
            "behavior": 6
        },
        "rsc": false,
        "portal": false,
        "radix": false,
        "polymorphic": true,
        "registry": true
    },
    "date-range-picker": {
        "tests": {
            "total": 8,
            "a11y": 1,
            "keyboard": 0,
            "behavior": 7
        },
        "rsc": false,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true
    },
    "dialog": {
        "tests": {
            "total": 11,
            "a11y": 0,
            "keyboard": 0,
            "behavior": 11
        },
        "rsc": false,
        "portal": true,
        "radix": true,
        "polymorphic": true,
        "registry": true
    },
    "divider": {
        "tests": {
            "total": 0,
            "a11y": 0,
            "keyboard": 0,
            "behavior": 0
        },
        "rsc": true,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true
    },
    "drawer": {
        "tests": {
            "total": 0,
            "a11y": 0,
            "keyboard": 0,
            "behavior": 0
        },
        "rsc": false,
        "portal": true,
        "radix": true,
        "polymorphic": true,
        "registry": true
    },
    "editable-text": {
        "tests": {
            "total": 10,
            "a11y": 0,
            "keyboard": 4,
            "behavior": 6
        },
        "rsc": false,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true
    },
    "entity-title": {
        "tests": {
            "total": 0,
            "a11y": 0,
            "keyboard": 0,
            "behavior": 0
        },
        "rsc": true,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true
    },
    "file-input": {
        "tests": {
            "total": 9,
            "a11y": 4,
            "keyboard": 0,
            "behavior": 5
        },
        "rsc": false,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true
    },
    "form-group": {
        "tests": {
            "total": 8,
            "a11y": 4,
            "keyboard": 0,
            "behavior": 4
        },
        "rsc": true,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true
    },
    "hotkeys": {
        "tests": {
            "total": 16,
            "a11y": 0,
            "keyboard": 4,
            "behavior": 12
        },
        "rsc": false,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true
    },
    "html-select": {
        "tests": {
            "total": 0,
            "a11y": 0,
            "keyboard": 0,
            "behavior": 0
        },
        "rsc": true,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true
    },
    "html-table": {
        "tests": {
            "total": 10,
            "a11y": 1,
            "keyboard": 0,
            "behavior": 9
        },
        "rsc": true,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true
    },
    "icon": {
        "tests": {
            "total": 0,
            "a11y": 0,
            "keyboard": 0,
            "behavior": 0
        },
        "rsc": true,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true
    },
    "input-group": {
        "tests": {
            "total": 0,
            "a11y": 0,
            "keyboard": 0,
            "behavior": 0
        },
        "rsc": true,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true
    },
    "link": {
        "tests": {
            "total": 0,
            "a11y": 0,
            "keyboard": 0,
            "behavior": 0
        },
        "rsc": true,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true
    },
    "menu": {
        "tests": {
            "total": 6,
            "a11y": 6,
            "keyboard": 0,
            "behavior": 0
        },
        "rsc": false,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true
    },
    "multi-select": {
        "tests": {
            "total": 3,
            "a11y": 2,
            "keyboard": 0,
            "behavior": 1
        },
        "rsc": false,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true
    },
    "multistep-dialog": {
        "tests": {
            "total": 12,
            "a11y": 1,
            "keyboard": 1,
            "behavior": 10
        },
        "rsc": false,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true
    },
    "navbar": {
        "tests": {
            "total": 9,
            "a11y": 1,
            "keyboard": 0,
            "behavior": 8
        },
        "rsc": true,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true
    },
    "non-ideal-state": {
        "tests": {
            "total": 0,
            "a11y": 0,
            "keyboard": 0,
            "behavior": 0
        },
        "rsc": true,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true
    },
    "numeric-input": {
        "tests": {
            "total": 4,
            "a11y": 2,
            "keyboard": 1,
            "behavior": 1
        },
        "rsc": false,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true
    },
    "omnibar": {
        "tests": {
            "total": 4,
            "a11y": 1,
            "keyboard": 2,
            "behavior": 1
        },
        "rsc": false,
        "portal": true,
        "radix": false,
        "polymorphic": false,
        "registry": true
    },
    "overflow-list": {
        "tests": {
            "total": 7,
            "a11y": 1,
            "keyboard": 0,
            "behavior": 6
        },
        "rsc": false,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true
    },
    "panel-stack": {
        "tests": {
            "total": 9,
            "a11y": 0,
            "keyboard": 0,
            "behavior": 9
        },
        "rsc": false,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true
    },
    "popover": {
        "tests": {
            "total": 3,
            "a11y": 0,
            "keyboard": 1,
            "behavior": 2
        },
        "rsc": false,
        "portal": true,
        "radix": true,
        "polymorphic": true,
        "registry": true
    },
    "portal": {
        "tests": {
            "total": 8,
            "a11y": 1,
            "keyboard": 0,
            "behavior": 7
        },
        "rsc": false,
        "portal": true,
        "radix": false,
        "polymorphic": false,
        "registry": true
    },
    "progress-bar": {
        "tests": {
            "total": 0,
            "a11y": 0,
            "keyboard": 0,
            "behavior": 0
        },
        "rsc": true,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true
    },
    "radio": {
        "tests": {
            "total": 10,
            "a11y": 2,
            "keyboard": 0,
            "behavior": 8
        },
        "rsc": false,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true
    },
    "resize-sensor": {
        "tests": {
            "total": 6,
            "a11y": 0,
            "keyboard": 0,
            "behavior": 6
        },
        "rsc": false,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true
    },
    "section": {
        "tests": {
            "total": 0,
            "a11y": 0,
            "keyboard": 0,
            "behavior": 0
        },
        "rsc": false,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true
    },
    "segmented-control": {
        "tests": {
            "total": 0,
            "a11y": 0,
            "keyboard": 0,
            "behavior": 0
        },
        "rsc": false,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true
    },
    "select": {
        "tests": {
            "total": 7,
            "a11y": 4,
            "keyboard": 1,
            "behavior": 2
        },
        "rsc": false,
        "portal": false,
        "radix": false,
        "polymorphic": true,
        "registry": true
    },
    "skeleton": {
        "tests": {
            "total": 0,
            "a11y": 0,
            "keyboard": 0,
            "behavior": 0
        },
        "rsc": true,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true
    },
    "slider": {
        "tests": {
            "total": 0,
            "a11y": 0,
            "keyboard": 0,
            "behavior": 0
        },
        "rsc": false,
        "portal": false,
        "radix": true,
        "polymorphic": false,
        "registry": true
    },
    "spinner": {
        "tests": {
            "total": 0,
            "a11y": 0,
            "keyboard": 0,
            "behavior": 0
        },
        "rsc": true,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true
    },
    "suggest": {
        "tests": {
            "total": 4,
            "a11y": 2,
            "keyboard": 1,
            "behavior": 1
        },
        "rsc": false,
        "portal": false,
        "radix": false,
        "polymorphic": true,
        "registry": true
    },
    "switch": {
        "tests": {
            "total": 0,
            "a11y": 0,
            "keyboard": 0,
            "behavior": 0
        },
        "rsc": false,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true
    },
    "tabs": {
        "tests": {
            "total": 17,
            "a11y": 2,
            "keyboard": 5,
            "behavior": 10
        },
        "rsc": false,
        "portal": false,
        "radix": true,
        "polymorphic": false,
        "registry": true
    },
    "tag": {
        "tests": {
            "total": 0,
            "a11y": 0,
            "keyboard": 0,
            "behavior": 0
        },
        "rsc": false,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true
    },
    "tag-input": {
        "tests": {
            "total": 0,
            "a11y": 0,
            "keyboard": 0,
            "behavior": 0
        },
        "rsc": false,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true
    },
    "text": {
        "tests": {
            "total": 0,
            "a11y": 0,
            "keyboard": 0,
            "behavior": 0
        },
        "rsc": false,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true
    },
    "text-area": {
        "tests": {
            "total": 9,
            "a11y": 1,
            "keyboard": 0,
            "behavior": 8
        },
        "rsc": false,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true
    },
    "time-picker": {
        "tests": {
            "total": 0,
            "a11y": 0,
            "keyboard": 0,
            "behavior": 0
        },
        "rsc": false,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true
    },
    "timezone-select": {
        "tests": {
            "total": 8,
            "a11y": 2,
            "keyboard": 0,
            "behavior": 6
        },
        "rsc": false,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true
    },
    "toast": {
        "tests": {
            "total": 0,
            "a11y": 0,
            "keyboard": 0,
            "behavior": 0
        },
        "rsc": false,
        "portal": false,
        "radix": true,
        "polymorphic": true,
        "registry": true
    },
    "tooltip": {
        "tests": {
            "total": 0,
            "a11y": 0,
            "keyboard": 0,
            "behavior": 0
        },
        "rsc": false,
        "portal": true,
        "radix": true,
        "polymorphic": true,
        "registry": true
    },
    "tree": {
        "tests": {
            "total": 0,
            "a11y": 0,
            "keyboard": 0,
            "behavior": 0
        },
        "rsc": false,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true
    }
};
