// AUTO-GENERATED by tools/gen-component-meta.mjs — do not edit by hand.
// Re-run after adding components or tests:  pnpm gen:meta

/** Per-component metadata for the showcase overview tiles and component pages. */
export interface ComponentMeta {
    /** Registry display title (e.g. "Button"); "" if not in the registry. */
    title: string;
    /** Registry one-line description; "" if not in the registry. */
    description: string;
    /** Test cases in the component's suite, bucketed by title-keyword heuristic. */
    tests: { total: number; a11y: number; keyboard: number; behavior: number };
    /** Server-renderable (no `"use client"` directive). */
    rsc: boolean;
    /** Renders into a portal — needs `dark` threading (see the overlays recipe). */
    portal: boolean;
    /** Backed by a `@radix-ui/*` headless primitive. */
    radix: boolean;
    /** Exposes `asChild` (Radix Slot polymorphism). */
    polymorphic: boolean;
    /** Distributable as owned-source via registry.json. */
    registry: boolean;
    /** Rendered (and thus a11y-audited) by the shared axe-smoke suite. */
    axe: boolean;
    /** Component-like exports the module ships (the compound-component family). */
    exports: string[];
    /** Other registry items this component builds on (component ids + foundations). */
    registryDependencies: string[];
    /** npm packages this component pulls in. */
    dependencies: string[];
}

export const COMPONENT_META: Record<string, ComponentMeta> = {
    "ai-explainability": {
        "title": "AiExplainability",
        "description": "A marker chip that flags AI-generated or AI-assisted content and reveals an explainability popover describing what the AI did.",
        "tests": {
            "total": 10,
            "a11y": 1,
            "keyboard": 2,
            "behavior": 7
        },
        "rsc": false,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true,
        "axe": true,
        "exports": [
            "AIExplainabilityDetails",
            "AIExplainability"
        ],
        "registryDependencies": [
            "icon",
            "link",
            "popover",
            "tag",
            "types",
            "utils",
            "tokens"
        ],
        "dependencies": []
    },
    "alert": {
        "title": "Alert",
        "description": "A modal confirm dialog — large icon, message, and confirm/cancel actions — for destructive or irreversible choices.",
        "tests": {
            "total": 2,
            "a11y": 1,
            "keyboard": 0,
            "behavior": 1
        },
        "rsc": false,
        "portal": true,
        "radix": true,
        "polymorphic": false,
        "registry": true,
        "axe": true,
        "exports": [
            "Alert"
        ],
        "registryDependencies": [
            "button",
            "icon",
            "types",
            "utils",
            "tokens"
        ],
        "dependencies": [
            "@radix-ui/react-dialog"
        ]
    },
    "anchor-button": {
        "title": "AnchorButton",
        "description": "An `<a>` styled exactly like Button, with anchor navigation semantics and proper disabled handling.",
        "tests": {
            "total": 13,
            "a11y": 4,
            "keyboard": 1,
            "behavior": 8
        },
        "rsc": false,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true,
        "axe": true,
        "exports": [
            "AnchorButton"
        ],
        "registryDependencies": [
            "button",
            "icon",
            "spinner",
            "utils",
            "tokens"
        ],
        "dependencies": [
            "class-variance-authority"
        ]
    },
    "breadcrumbs": {
        "title": "Breadcrumbs",
        "description": "A navigational trail of links that collapses into an overflow menu when the path is too long to fit.",
        "tests": {
            "total": 0,
            "a11y": 0,
            "keyboard": 0,
            "behavior": 0
        },
        "rsc": false,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true,
        "axe": false,
        "exports": [
            "Breadcrumb",
            "Breadcrumbs"
        ],
        "registryDependencies": [
            "icon",
            "utils",
            "tokens"
        ],
        "dependencies": []
    },
    "button": {
        "title": "Button",
        "description": "The core action control — five intents, fill/outlined/minimal variants, sizes, icons, and a loading state.",
        "tests": {
            "total": 0,
            "a11y": 0,
            "keyboard": 0,
            "behavior": 0
        },
        "rsc": false,
        "portal": false,
        "radix": true,
        "polymorphic": true,
        "registry": true,
        "axe": true,
        "exports": [
            "Button"
        ],
        "registryDependencies": [
            "icon",
            "spinner",
            "types",
            "utils",
            "tokens"
        ],
        "dependencies": [
            "@radix-ui/react-slot",
            "class-variance-authority"
        ]
    },
    "button-group": {
        "title": "ButtonGroup",
        "description": "Attaches a row or column of Buttons into one segmented control, collapsing the inner radii and shared borders.",
        "tests": {
            "total": 9,
            "a11y": 1,
            "keyboard": 0,
            "behavior": 8
        },
        "rsc": false,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true,
        "axe": true,
        "exports": [
            "ButtonGroup"
        ],
        "registryDependencies": [
            "button",
            "utils",
            "tokens"
        ],
        "dependencies": [
            "class-variance-authority"
        ]
    },
    "callout": {
        "title": "Callout",
        "description": "A boxed inline message with an intent color, leading icon, and optional heading for page-level notices.",
        "tests": {
            "total": 0,
            "a11y": 0,
            "keyboard": 0,
            "behavior": 0
        },
        "rsc": true,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true,
        "axe": true,
        "exports": [
            "Callout"
        ],
        "registryDependencies": [
            "icon",
            "types",
            "utils",
            "tokens"
        ],
        "dependencies": []
    },
    "card": {
        "title": "Card",
        "description": "An elevated surface container with selectable elevation and an optional interactive hover lift.",
        "tests": {
            "total": 0,
            "a11y": 0,
            "keyboard": 0,
            "behavior": 0
        },
        "rsc": true,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true,
        "axe": false,
        "exports": [
            "Card"
        ],
        "registryDependencies": [
            "utils",
            "tokens"
        ],
        "dependencies": [
            "class-variance-authority"
        ]
    },
    "card-list": {
        "title": "CardList",
        "description": "A bordered, flush-stacked list of Cards with hover and interactive states for selectable rows.",
        "tests": {
            "total": 0,
            "a11y": 0,
            "keyboard": 0,
            "behavior": 0
        },
        "rsc": true,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true,
        "axe": true,
        "exports": [
            "CardList"
        ],
        "registryDependencies": [
            "card",
            "utils",
            "tokens"
        ],
        "dependencies": []
    },
    "checkbox": {
        "title": "Checkbox",
        "description": "A labeled checkbox with indeterminate state, sizes, and inline or block layout.",
        "tests": {
            "total": 0,
            "a11y": 0,
            "keyboard": 0,
            "behavior": 0
        },
        "rsc": false,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true,
        "axe": true,
        "exports": [
            "Checkbox"
        ],
        "registryDependencies": [
            "icon",
            "utils",
            "tokens"
        ],
        "dependencies": []
    },
    "collapse": {
        "title": "Collapse",
        "description": "An animated height transition that smoothly expands and collapses its content region.",
        "tests": {
            "total": 0,
            "a11y": 0,
            "keyboard": 0,
            "behavior": 0
        },
        "rsc": false,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true,
        "axe": false,
        "exports": [
            "Collapse"
        ],
        "registryDependencies": [
            "utils",
            "tokens"
        ],
        "dependencies": []
    },
    "context-menu": {
        "title": "ContextMenu",
        "description": "A right-click popup menu — a Radix context-menu trigger wrapping mithril's Menu surface.",
        "tests": {
            "total": 3,
            "a11y": 1,
            "keyboard": 2,
            "behavior": 0
        },
        "rsc": false,
        "portal": true,
        "radix": true,
        "polymorphic": true,
        "registry": true,
        "axe": false,
        "exports": [
            "ContextMenu"
        ],
        "registryDependencies": [
            "menu",
            "utils",
            "tokens"
        ],
        "dependencies": [
            "@radix-ui/react-context-menu"
        ]
    },
    "control-base": {
        "title": "ControlBase",
        "description": "The shared label / hidden-input / indicator primitive behind Checkbox, Radio, and Switch.",
        "tests": {
            "total": 0,
            "a11y": 0,
            "keyboard": 0,
            "behavior": 0
        },
        "rsc": true,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true,
        "axe": false,
        "exports": [
            "ControlBase"
        ],
        "registryDependencies": [
            "utils",
            "tokens"
        ],
        "dependencies": []
    },
    "control-card": {
        "title": "ControlCard",
        "description": "A Card whose entire surface is a selectable Checkbox, Radio, or Switch label.",
        "tests": {
            "total": 0,
            "a11y": 0,
            "keyboard": 0,
            "behavior": 0
        },
        "rsc": false,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true,
        "axe": false,
        "exports": [
            "CheckboxCard",
            "RadioCard",
            "SwitchCard"
        ],
        "registryDependencies": [
            "card",
            "checkbox",
            "radio",
            "switch",
            "utils",
            "tokens"
        ],
        "dependencies": []
    },
    "control-group": {
        "title": "ControlGroup",
        "description": "A flex layout wrapper that attaches form controls — inputs, selects, buttons — into one row or column.",
        "tests": {
            "total": 12,
            "a11y": 1,
            "keyboard": 0,
            "behavior": 11
        },
        "rsc": true,
        "portal": false,
        "radix": false,
        "polymorphic": true,
        "registry": true,
        "axe": false,
        "exports": [
            "ControlGroup"
        ],
        "registryDependencies": [
            "utils",
            "tokens"
        ],
        "dependencies": [
            "class-variance-authority"
        ]
    },
    "data-table": {
        "title": "DataTable",
        "description": "A virtualized data grid with sortable, resizable columns and row selection, built on TanStack Table.",
        "tests": {
            "total": 76,
            "a11y": 3,
            "keyboard": 11,
            "behavior": 62
        },
        "rsc": false,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true,
        "axe": false,
        "exports": [
            "DataTable"
        ],
        "registryDependencies": [
            "icon",
            "skeleton",
            "utils",
            "tokens"
        ],
        "dependencies": [
            "@tanstack/react-table",
            "@tanstack/react-virtual"
        ]
    },
    "date-input": {
        "title": "DateInput",
        "description": "A text field that opens a DatePicker popover for typing or picking a single date.",
        "tests": {
            "total": 0,
            "a11y": 0,
            "keyboard": 0,
            "behavior": 0
        },
        "rsc": false,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true,
        "axe": false,
        "exports": [
            "DateInput"
        ],
        "registryDependencies": [
            "date-picker",
            "icon",
            "input-group",
            "popover",
            "time-picker",
            "utils",
            "tokens"
        ],
        "dependencies": []
    },
    "date-picker": {
        "title": "DatePicker",
        "description": "A single-date calendar with month/year navigation and optional time selection, on react-day-picker.",
        "tests": {
            "total": 0,
            "a11y": 0,
            "keyboard": 0,
            "behavior": 0
        },
        "rsc": false,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true,
        "axe": false,
        "exports": [
            "DatePicker"
        ],
        "registryDependencies": [
            "html-select",
            "icon",
            "time-picker",
            "utils",
            "tokens"
        ],
        "dependencies": [
            "react-day-picker"
        ]
    },
    "date-range-input": {
        "title": "DateRangeInput",
        "description": "Two linked text fields sharing one DateRangePicker popover to capture a start-and-end range.",
        "tests": {
            "total": 8,
            "a11y": 2,
            "keyboard": 0,
            "behavior": 6
        },
        "rsc": false,
        "portal": false,
        "radix": false,
        "polymorphic": true,
        "registry": true,
        "axe": false,
        "exports": [
            "DateRangeInput"
        ],
        "registryDependencies": [
            "date-range-picker",
            "input-group",
            "popover",
            "utils",
            "tokens"
        ],
        "dependencies": []
    },
    "date-range-picker": {
        "title": "DateRangePicker",
        "description": "Two side-by-side month calendars for selecting a start-to-end date range.",
        "tests": {
            "total": 8,
            "a11y": 1,
            "keyboard": 0,
            "behavior": 7
        },
        "rsc": false,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true,
        "axe": false,
        "exports": [
            "DateRangePicker"
        ],
        "registryDependencies": [
            "html-select",
            "icon",
            "utils",
            "tokens"
        ],
        "dependencies": [
            "react-day-picker"
        ]
    },
    "dialog": {
        "title": "Dialog",
        "description": "A modal overlay with header, body, and footer — focus-trapped and scroll-locked, on Radix Dialog.",
        "tests": {
            "total": 11,
            "a11y": 0,
            "keyboard": 0,
            "behavior": 11
        },
        "rsc": false,
        "portal": true,
        "radix": true,
        "polymorphic": true,
        "registry": true,
        "axe": true,
        "exports": [
            "Dialog",
            "DialogBody",
            "DialogFooter"
        ],
        "registryDependencies": [
            "button",
            "icon",
            "utils",
            "tokens"
        ],
        "dependencies": [
            "@radix-ui/react-dialog"
        ]
    },
    "divider": {
        "title": "Divider",
        "description": "A thin rule that separates content horizontally or vertically.",
        "tests": {
            "total": 0,
            "a11y": 0,
            "keyboard": 0,
            "behavior": 0
        },
        "rsc": true,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true,
        "axe": false,
        "exports": [
            "Divider"
        ],
        "registryDependencies": [
            "utils",
            "tokens"
        ],
        "dependencies": [
            "class-variance-authority"
        ]
    },
    "drawer": {
        "title": "Drawer",
        "description": "An overlay panel anchored to a screen edge, focus-trapped and scroll-locked, on Radix Dialog.",
        "tests": {
            "total": 0,
            "a11y": 0,
            "keyboard": 0,
            "behavior": 0
        },
        "rsc": false,
        "portal": true,
        "radix": true,
        "polymorphic": true,
        "registry": true,
        "axe": true,
        "exports": [
            "Drawer",
            "DrawerBody",
            "DrawerFooter"
        ],
        "registryDependencies": [
            "button",
            "icon",
            "utils",
            "tokens"
        ],
        "dependencies": [
            "@radix-ui/react-dialog"
        ]
    },
    "editable-text": {
        "title": "EditableText",
        "description": "Text that turns into an inline input on click and commits on blur or Enter.",
        "tests": {
            "total": 10,
            "a11y": 0,
            "keyboard": 4,
            "behavior": 6
        },
        "rsc": false,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true,
        "axe": false,
        "exports": [
            "EditableText"
        ],
        "registryDependencies": [
            "types",
            "utils",
            "tokens"
        ],
        "dependencies": []
    },
    "entity-title": {
        "title": "EntityTitle",
        "description": "A title block pairing an icon or avatar with a heading, subtitle, and optional tags.",
        "tests": {
            "total": 0,
            "a11y": 0,
            "keyboard": 0,
            "behavior": 0
        },
        "rsc": true,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true,
        "axe": false,
        "exports": [
            "EntityTitle"
        ],
        "registryDependencies": [
            "icon",
            "skeleton",
            "utils",
            "tokens"
        ],
        "dependencies": []
    },
    "file-dropzone": {
        "title": "FileDropzone",
        "description": "A drag-and-drop surface for multi-file uploads, with previews and validation, built on react-dropzone.",
        "tests": {
            "total": 9,
            "a11y": 1,
            "keyboard": 0,
            "behavior": 8
        },
        "rsc": false,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true,
        "axe": false,
        "exports": [
            "FileDropzone"
        ],
        "registryDependencies": [
            "icon",
            "progress-bar",
            "utils",
            "tokens"
        ],
        "dependencies": [
            "react-dropzone"
        ]
    },
    "file-input": {
        "title": "FileInput",
        "description": "A styled file picker showing a Browse button and the selected file's name.",
        "tests": {
            "total": 9,
            "a11y": 4,
            "keyboard": 0,
            "behavior": 5
        },
        "rsc": false,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true,
        "axe": false,
        "exports": [
            "FileInput"
        ],
        "registryDependencies": [
            "utils",
            "tokens"
        ],
        "dependencies": []
    },
    "form-group": {
        "title": "FormGroup",
        "description": "Wraps a label, helper text, and a control into one labeled — and optionally inline — form field.",
        "tests": {
            "total": 8,
            "a11y": 4,
            "keyboard": 0,
            "behavior": 4
        },
        "rsc": true,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true,
        "axe": false,
        "exports": [
            "Label",
            "FormGroup"
        ],
        "registryDependencies": [
            "types",
            "utils",
            "tokens"
        ],
        "dependencies": []
    },
    "hotkeys": {
        "title": "Hotkeys",
        "description": "A keyboard-shortcut system — KeyCombo key-cap rendering plus a global shortcuts help dialog.",
        "tests": {
            "total": 16,
            "a11y": 0,
            "keyboard": 4,
            "behavior": 12
        },
        "rsc": false,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true,
        "axe": false,
        "exports": [
            "KeyCombo",
            "HotkeysDialog",
            "HotkeysProvider"
        ],
        "registryDependencies": [
            "dialog",
            "icon",
            "utils",
            "tokens"
        ],
        "dependencies": []
    },
    "html-select": {
        "title": "HTMLSelect",
        "description": "A native `<select>` restyled to the system, with a chevron affordance and matching sizes.",
        "tests": {
            "total": 0,
            "a11y": 0,
            "keyboard": 0,
            "behavior": 0
        },
        "rsc": true,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true,
        "axe": false,
        "exports": [
            "HTMLSelect"
        ],
        "registryDependencies": [
            "icon",
            "utils",
            "tokens"
        ],
        "dependencies": []
    },
    "html-table": {
        "title": "HTMLTable",
        "description": "A styled wrapper for native `<table>` markup — striped, bordered, and compact variants.",
        "tests": {
            "total": 10,
            "a11y": 1,
            "keyboard": 0,
            "behavior": 9
        },
        "rsc": true,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true,
        "axe": true,
        "exports": [
            "HTMLTable"
        ],
        "registryDependencies": [
            "utils",
            "tokens"
        ],
        "dependencies": [
            "class-variance-authority"
        ]
    },
    "icon": {
        "title": "Icon",
        "description": "Renders any of the 706 vendored Blueprint glyphs by name or imported object, at a given size and color.",
        "tests": {
            "total": 0,
            "a11y": 0,
            "keyboard": 0,
            "behavior": 0
        },
        "rsc": true,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true,
        "axe": false,
        "exports": [
            "Icon"
        ],
        "registryDependencies": [
            "types",
            "utils",
            "tokens"
        ],
        "dependencies": []
    },
    "input-group": {
        "title": "InputGroup",
        "description": "A text input with leading or trailing icons, buttons, or spinners placed inside the field.",
        "tests": {
            "total": 0,
            "a11y": 0,
            "keyboard": 0,
            "behavior": 0
        },
        "rsc": true,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true,
        "axe": true,
        "exports": [
            "InputGroup"
        ],
        "registryDependencies": [
            "icon",
            "types",
            "utils",
            "tokens"
        ],
        "dependencies": [
            "class-variance-authority"
        ]
    },
    "link": {
        "title": "Link",
        "description": "An inline anchor with the system's link styling, focus ring, and optional icon.",
        "tests": {
            "total": 0,
            "a11y": 0,
            "keyboard": 0,
            "behavior": 0
        },
        "rsc": true,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true,
        "axe": false,
        "exports": [
            "Link"
        ],
        "registryDependencies": [
            "utils",
            "tokens"
        ],
        "dependencies": [
            "class-variance-authority"
        ]
    },
    "menu": {
        "title": "Menu",
        "description": "A standalone styled list of items, dividers, and submenus — compose inside a Popover for a dropdown.",
        "tests": {
            "total": 6,
            "a11y": 6,
            "keyboard": 0,
            "behavior": 0
        },
        "rsc": false,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true,
        "axe": true,
        "exports": [
            "Menu",
            "MenuItem",
            "MenuDivider"
        ],
        "registryDependencies": [
            "icon",
            "types",
            "utils",
            "tokens"
        ],
        "dependencies": []
    },
    "multi-select": {
        "title": "MultiSelect",
        "description": "A tag-chip input that filters a dropdown and accumulates multiple selected items.",
        "tests": {
            "total": 3,
            "a11y": 2,
            "keyboard": 0,
            "behavior": 1
        },
        "rsc": false,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true,
        "axe": true,
        "exports": [
            "MultiSelect"
        ],
        "registryDependencies": [
            "icon",
            "menu",
            "popover",
            "select",
            "tag",
            "types",
            "utils",
            "tokens"
        ],
        "dependencies": []
    },
    "multistep-dialog": {
        "title": "MultistepDialog",
        "description": "A wizard Dialog with a numbered step rail and back/next navigation across ordered steps.",
        "tests": {
            "total": 16,
            "a11y": 1,
            "keyboard": 1,
            "behavior": 14
        },
        "rsc": false,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true,
        "axe": true,
        "exports": [
            "DialogStep",
            "MultistepDialog"
        ],
        "registryDependencies": [
            "button",
            "dialog",
            "utils",
            "tokens"
        ],
        "dependencies": []
    },
    "navbar": {
        "title": "Navbar",
        "description": "A fixed-height top bar with left and right groups, headings, and dividers for app chrome.",
        "tests": {
            "total": 9,
            "a11y": 1,
            "keyboard": 0,
            "behavior": 8
        },
        "rsc": true,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true,
        "axe": false,
        "exports": [
            "Navbar",
            "NavbarGroup",
            "NavbarHeading",
            "NavbarDivider"
        ],
        "registryDependencies": [
            "utils",
            "tokens"
        ],
        "dependencies": []
    },
    "non-ideal-state": {
        "title": "NonIdealState",
        "description": "An empty / error / loading placeholder that centers an icon, title, description, and action.",
        "tests": {
            "total": 0,
            "a11y": 0,
            "keyboard": 0,
            "behavior": 0
        },
        "rsc": true,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true,
        "axe": false,
        "exports": [
            "NonIdealState"
        ],
        "registryDependencies": [
            "icon",
            "utils",
            "tokens"
        ],
        "dependencies": [
            "class-variance-authority"
        ]
    },
    "numeric-input": {
        "title": "NumericInput",
        "description": "A number field with increment/decrement steppers, clamping, and keyboard adjustment.",
        "tests": {
            "total": 4,
            "a11y": 2,
            "keyboard": 1,
            "behavior": 1
        },
        "rsc": false,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true,
        "axe": true,
        "exports": [
            "NumericInput"
        ],
        "registryDependencies": [
            "icon",
            "input-group",
            "utils",
            "tokens"
        ],
        "dependencies": []
    },
    "omnibar": {
        "title": "Omnibar",
        "description": "A command-palette overlay — a top-pinned search field over a filtered result menu.",
        "tests": {
            "total": 4,
            "a11y": 1,
            "keyboard": 2,
            "behavior": 1
        },
        "rsc": false,
        "portal": true,
        "radix": false,
        "polymorphic": false,
        "registry": true,
        "axe": false,
        "exports": [
            "Omnibar"
        ],
        "registryDependencies": [
            "icon",
            "input-group",
            "menu",
            "select",
            "utils",
            "tokens"
        ],
        "dependencies": []
    },
    "overflow-list": {
        "title": "OverflowList",
        "description": "A horizontal list that collapses the items that don't fit into a trailing overflow renderer.",
        "tests": {
            "total": 7,
            "a11y": 1,
            "keyboard": 0,
            "behavior": 6
        },
        "rsc": false,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true,
        "axe": false,
        "exports": [
            "OverflowList"
        ],
        "registryDependencies": [
            "resize-sensor",
            "utils",
            "tokens"
        ],
        "dependencies": []
    },
    "panel-stack": {
        "title": "PanelStack",
        "description": "An animated stack of panels with push/pop navigation and a back-to-previous header.",
        "tests": {
            "total": 9,
            "a11y": 0,
            "keyboard": 0,
            "behavior": 9
        },
        "rsc": false,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true,
        "axe": false,
        "exports": [
            "PanelStack"
        ],
        "registryDependencies": [
            "button",
            "icon",
            "utils",
            "tokens"
        ],
        "dependencies": []
    },
    "popover": {
        "title": "Popover",
        "description": "A floating panel anchored to a trigger, with arrow, placement, and dismissal, on Radix Popover.",
        "tests": {
            "total": 3,
            "a11y": 0,
            "keyboard": 1,
            "behavior": 2
        },
        "rsc": false,
        "portal": true,
        "radix": true,
        "polymorphic": true,
        "registry": true,
        "axe": true,
        "exports": [
            "Popover",
            "MenuPopover"
        ],
        "registryDependencies": [
            "utils",
            "tokens"
        ],
        "dependencies": [
            "@radix-ui/react-popover"
        ]
    },
    "portal": {
        "title": "Portal",
        "description": "Renders children into a detached DOM node to escape `overflow` and `z-index` stacking.",
        "tests": {
            "total": 8,
            "a11y": 1,
            "keyboard": 0,
            "behavior": 7
        },
        "rsc": false,
        "portal": true,
        "radix": false,
        "polymorphic": false,
        "registry": true,
        "axe": false,
        "exports": [
            "PortalProvider",
            "Portal"
        ],
        "registryDependencies": [
            "utils",
            "tokens"
        ],
        "dependencies": []
    },
    "progress-bar": {
        "title": "ProgressBar",
        "description": "A horizontal track with a determinate fill or indeterminate animation, colored per intent.",
        "tests": {
            "total": 0,
            "a11y": 0,
            "keyboard": 0,
            "behavior": 0
        },
        "rsc": true,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true,
        "axe": false,
        "exports": [
            "ProgressBar"
        ],
        "registryDependencies": [
            "types",
            "utils",
            "tokens"
        ],
        "dependencies": []
    },
    "radio": {
        "title": "Radio",
        "description": "A labeled radio control, plus RadioGroup for single-choice selection.",
        "tests": {
            "total": 10,
            "a11y": 2,
            "keyboard": 0,
            "behavior": 8
        },
        "rsc": false,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true,
        "axe": true,
        "exports": [
            "RadioGroup",
            "Radio"
        ],
        "registryDependencies": [
            "utils",
            "tokens"
        ],
        "dependencies": []
    },
    "resize-sensor": {
        "title": "ResizeSensor",
        "description": "A headless helper that observes an element's size and fires a callback whenever it changes.",
        "tests": {
            "total": 6,
            "a11y": 0,
            "keyboard": 0,
            "behavior": 6
        },
        "rsc": false,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true,
        "axe": false,
        "exports": [
            "ResizeSensor"
        ],
        "registryDependencies": [
            "tokens"
        ],
        "dependencies": []
    },
    "section": {
        "title": "Section",
        "description": "A titled content container with a header, optional right-side controls, and a collapsible body.",
        "tests": {
            "total": 0,
            "a11y": 0,
            "keyboard": 0,
            "behavior": 0
        },
        "rsc": false,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true,
        "axe": false,
        "exports": [
            "Section",
            "SectionCard"
        ],
        "registryDependencies": [
            "card",
            "collapse",
            "icon",
            "text",
            "utils",
            "tokens"
        ],
        "dependencies": []
    },
    "segmented-control": {
        "title": "SegmentedControl",
        "description": "A pill-track toggle of mutually exclusive options — tabs styled as a single control.",
        "tests": {
            "total": 0,
            "a11y": 0,
            "keyboard": 0,
            "behavior": 0
        },
        "rsc": false,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true,
        "axe": false,
        "exports": [
            "SegmentedControl"
        ],
        "registryDependencies": [
            "button",
            "icon",
            "types",
            "utils",
            "tokens"
        ],
        "dependencies": [
            "class-variance-authority"
        ]
    },
    "select": {
        "title": "Select",
        "description": "A filterable dropdown — type to search, arrow-key navigate, and pick a single item.",
        "tests": {
            "total": 7,
            "a11y": 4,
            "keyboard": 1,
            "behavior": 2
        },
        "rsc": false,
        "portal": false,
        "radix": false,
        "polymorphic": true,
        "registry": true,
        "axe": false,
        "exports": [
            "Select"
        ],
        "registryDependencies": [
            "icon",
            "input-group",
            "menu",
            "popover",
            "utils",
            "tokens"
        ],
        "dependencies": []
    },
    "skeleton": {
        "title": "Skeleton",
        "description": "A shimmering placeholder modifier that stands in for content while it loads.",
        "tests": {
            "total": 0,
            "a11y": 0,
            "keyboard": 0,
            "behavior": 0
        },
        "rsc": true,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true,
        "axe": false,
        "exports": [
            "Skeleton"
        ],
        "registryDependencies": [
            "skeleton",
            "utils",
            "tokens"
        ],
        "dependencies": []
    },
    "slider": {
        "title": "Slider",
        "description": "A draggable track for choosing a numeric value or range, with labels and tick marks.",
        "tests": {
            "total": 0,
            "a11y": 0,
            "keyboard": 0,
            "behavior": 0
        },
        "rsc": false,
        "portal": false,
        "radix": true,
        "polymorphic": false,
        "registry": true,
        "axe": true,
        "exports": [
            "Slider"
        ],
        "registryDependencies": [
            "types",
            "utils",
            "tokens"
        ],
        "dependencies": [
            "@radix-ui/react-slider"
        ]
    },
    "spinner": {
        "title": "Spinner",
        "description": "An indeterminate circular loading indicator, sized and intent-colored.",
        "tests": {
            "total": 0,
            "a11y": 0,
            "keyboard": 0,
            "behavior": 0
        },
        "rsc": true,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true,
        "axe": false,
        "exports": [
            "Spinner"
        ],
        "registryDependencies": [
            "types",
            "utils",
            "tokens"
        ],
        "dependencies": []
    },
    "suggest": {
        "title": "Suggest",
        "description": "A typeahead where the input itself filters a dropdown and fills with the chosen item.",
        "tests": {
            "total": 4,
            "a11y": 2,
            "keyboard": 1,
            "behavior": 1
        },
        "rsc": false,
        "portal": false,
        "radix": false,
        "polymorphic": true,
        "registry": true,
        "axe": true,
        "exports": [
            "Suggest"
        ],
        "registryDependencies": [
            "input-group",
            "menu",
            "popover",
            "select",
            "utils",
            "tokens"
        ],
        "dependencies": []
    },
    "switch": {
        "title": "Switch",
        "description": "A toggle switch for on/off state, with labels and sizes — a Checkbox alternative.",
        "tests": {
            "total": 0,
            "a11y": 0,
            "keyboard": 0,
            "behavior": 0
        },
        "rsc": false,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true,
        "axe": true,
        "exports": [
            "Switch"
        ],
        "registryDependencies": [
            "utils",
            "tokens"
        ],
        "dependencies": []
    },
    "tabs": {
        "title": "Tabs",
        "description": "A tabbed panel switcher with an animated active indicator, on Radix Tabs.",
        "tests": {
            "total": 17,
            "a11y": 2,
            "keyboard": 5,
            "behavior": 10
        },
        "rsc": false,
        "portal": false,
        "radix": true,
        "polymorphic": false,
        "registry": true,
        "axe": true,
        "exports": [
            "Tabs",
            "Tab"
        ],
        "registryDependencies": [
            "icon",
            "utils",
            "tokens"
        ],
        "dependencies": [
            "@radix-ui/react-tabs"
        ]
    },
    "tag": {
        "title": "Tag",
        "description": "A compact label chip with intents, solid or minimal styles, an icon, and an optional remove button.",
        "tests": {
            "total": 0,
            "a11y": 0,
            "keyboard": 0,
            "behavior": 0
        },
        "rsc": false,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true,
        "axe": true,
        "exports": [
            "Tag"
        ],
        "registryDependencies": [
            "icon",
            "types",
            "utils",
            "tokens"
        ],
        "dependencies": []
    },
    "tag-input": {
        "title": "TagInput",
        "description": "A field that collects free-text values as removable Tag chips.",
        "tests": {
            "total": 0,
            "a11y": 0,
            "keyboard": 0,
            "behavior": 0
        },
        "rsc": false,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true,
        "axe": false,
        "exports": [
            "TagInput"
        ],
        "registryDependencies": [
            "icon",
            "tag",
            "types",
            "utils",
            "tokens"
        ],
        "dependencies": []
    },
    "text": {
        "title": "Text",
        "description": "Typographic text tiers — headings, body, muted — mapped to the system's type scale.",
        "tests": {
            "total": 0,
            "a11y": 0,
            "keyboard": 0,
            "behavior": 0
        },
        "rsc": false,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true,
        "axe": false,
        "exports": [
            "Text"
        ],
        "registryDependencies": [
            "utils",
            "tokens"
        ],
        "dependencies": [
            "class-variance-authority"
        ]
    },
    "text-area": {
        "title": "TextArea",
        "description": "A multi-line text field with sizes, fill, and auto-resize support.",
        "tests": {
            "total": 9,
            "a11y": 1,
            "keyboard": 0,
            "behavior": 8
        },
        "rsc": false,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true,
        "axe": false,
        "exports": [
            "TextArea"
        ],
        "registryDependencies": [
            "types",
            "utils",
            "tokens"
        ],
        "dependencies": [
            "class-variance-authority"
        ]
    },
    "time-picker": {
        "title": "TimePicker",
        "description": "A time field with hour/minute/second steppers and optional AM/PM, to a set precision.",
        "tests": {
            "total": 0,
            "a11y": 0,
            "keyboard": 0,
            "behavior": 0
        },
        "rsc": false,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true,
        "axe": true,
        "exports": [
            "TimePicker"
        ],
        "registryDependencies": [
            "html-select",
            "icon",
            "utils",
            "tokens"
        ],
        "dependencies": []
    },
    "timezone-select": {
        "title": "TimezoneSelect",
        "description": "A Select specialized for IANA timezones, searchable by city and UTC offset.",
        "tests": {
            "total": 8,
            "a11y": 2,
            "keyboard": 0,
            "behavior": 6
        },
        "rsc": false,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true,
        "axe": false,
        "exports": [
            "TimezoneSelect",
            "MINIMAL_IANA_CODES"
        ],
        "registryDependencies": [
            "button",
            "icon",
            "menu",
            "select",
            "tokens"
        ],
        "dependencies": []
    },
    "toast": {
        "title": "Toast",
        "description": "A transient notification card plus a Toaster that stacks and auto-dismisses them, on Radix Toast.",
        "tests": {
            "total": 0,
            "a11y": 0,
            "keyboard": 0,
            "behavior": 0
        },
        "rsc": false,
        "portal": false,
        "radix": true,
        "polymorphic": true,
        "registry": true,
        "axe": false,
        "exports": [
            "Toast",
            "ToastProvider",
            "Toaster"
        ],
        "registryDependencies": [
            "icon",
            "types",
            "utils",
            "tokens"
        ],
        "dependencies": [
            "@radix-ui/react-toast"
        ]
    },
    "tooltip": {
        "title": "Tooltip",
        "description": "A small inverted hover/focus label anchored to its trigger, on Radix Tooltip.",
        "tests": {
            "total": 0,
            "a11y": 0,
            "keyboard": 0,
            "behavior": 0
        },
        "rsc": false,
        "portal": true,
        "radix": true,
        "polymorphic": true,
        "registry": true,
        "axe": false,
        "exports": [
            "TooltipProvider",
            "Tooltip"
        ],
        "registryDependencies": [
            "types",
            "utils",
            "tokens"
        ],
        "dependencies": [
            "@radix-ui/react-tooltip"
        ]
    },
    "tree": {
        "title": "Tree",
        "description": "A nested, expandable tree of nodes with icons, selection, and caret toggles.",
        "tests": {
            "total": 0,
            "a11y": 0,
            "keyboard": 0,
            "behavior": 0
        },
        "rsc": false,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true,
        "axe": false,
        "exports": [
            "Tree"
        ],
        "registryDependencies": [
            "collapse",
            "icon",
            "utils",
            "tokens"
        ],
        "dependencies": []
    }
};
