// AUTO-GENERATED by tools/gen-component-meta.mjs — do not edit by hand.
// Re-run after adding components or tests:  pnpm gen:meta

/** Per-component metadata for the showcase overview tiles and component pages. */
export interface ComponentMeta {
    /** Registry display title (e.g. "Button"); "" if not in the registry. */
    title: string;
    /** Registry one-line description; "" if not in the registry. */
    description: string;
    /** Test cases in the component's suite, bucketed by title-keyword heuristic. */
    tests: { total: number; a11y: number; keyboard: number; behavior: number };
    /** Server-renderable (no `"use client"` directive). */
    rsc: boolean;
    /** Renders into a portal — needs `dark` threading (see the overlays recipe). */
    portal: boolean;
    /** Backed by a `@radix-ui/*` headless primitive. */
    radix: boolean;
    /** Exposes `asChild` (Radix Slot polymorphism). */
    polymorphic: boolean;
    /** Distributable as owned-source via registry.json. */
    registry: boolean;
    /** Rendered (and thus a11y-audited) by the shared axe-smoke suite. */
    axe: boolean;
    /** Component-like exports the module ships (the compound-component family). */
    exports: string[];
    /** Other registry items this component builds on (component ids + foundations). */
    registryDependencies: string[];
    /** npm packages this component pulls in. */
    dependencies: string[];
}

export const COMPONENT_META: Record<string, ComponentMeta> = {
    "ai-label": {
        "title": "AILabel",
        "description": "AILabel — Blueprint-faithful, built on CVA.",
        "tests": {
            "total": 10,
            "a11y": 1,
            "keyboard": 2,
            "behavior": 7
        },
        "rsc": false,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true,
        "axe": true,
        "exports": [
            "AILabelExplanation",
            "AILabel"
        ],
        "registryDependencies": [
            "icon",
            "link",
            "popover",
            "tag",
            "types",
            "utils",
            "tokens"
        ],
        "dependencies": []
    },
    "alert": {
        "title": "Alert",
        "description": "Alert — Blueprint-faithful, built on CVA + Radix.",
        "tests": {
            "total": 2,
            "a11y": 1,
            "keyboard": 0,
            "behavior": 1
        },
        "rsc": false,
        "portal": true,
        "radix": true,
        "polymorphic": false,
        "registry": true,
        "axe": true,
        "exports": [
            "Alert"
        ],
        "registryDependencies": [
            "button",
            "icon",
            "types",
            "utils",
            "tokens"
        ],
        "dependencies": [
            "@radix-ui/react-dialog"
        ]
    },
    "anchor-button": {
        "title": "AnchorButton",
        "description": "AnchorButton — Blueprint-faithful, built on CVA.",
        "tests": {
            "total": 13,
            "a11y": 4,
            "keyboard": 1,
            "behavior": 8
        },
        "rsc": false,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true,
        "axe": true,
        "exports": [
            "AnchorButton"
        ],
        "registryDependencies": [
            "button",
            "icon",
            "spinner",
            "utils",
            "tokens"
        ],
        "dependencies": [
            "class-variance-authority"
        ]
    },
    "breadcrumbs": {
        "title": "Breadcrumbs",
        "description": "Breadcrumbs — Blueprint-faithful, built on CVA.",
        "tests": {
            "total": 0,
            "a11y": 0,
            "keyboard": 0,
            "behavior": 0
        },
        "rsc": false,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true,
        "axe": false,
        "exports": [
            "Breadcrumb",
            "Breadcrumbs"
        ],
        "registryDependencies": [
            "icon",
            "utils",
            "tokens"
        ],
        "dependencies": []
    },
    "button": {
        "title": "Button",
        "description": "Button — Blueprint-faithful, built on CVA + Radix.",
        "tests": {
            "total": 0,
            "a11y": 0,
            "keyboard": 0,
            "behavior": 0
        },
        "rsc": false,
        "portal": false,
        "radix": true,
        "polymorphic": true,
        "registry": true,
        "axe": true,
        "exports": [
            "Button"
        ],
        "registryDependencies": [
            "icon",
            "spinner",
            "types",
            "utils",
            "tokens"
        ],
        "dependencies": [
            "@radix-ui/react-slot",
            "class-variance-authority"
        ]
    },
    "button-group": {
        "title": "ButtonGroup",
        "description": "ButtonGroup — Blueprint-faithful, built on CVA.",
        "tests": {
            "total": 9,
            "a11y": 1,
            "keyboard": 0,
            "behavior": 8
        },
        "rsc": false,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true,
        "axe": true,
        "exports": [
            "ButtonGroup"
        ],
        "registryDependencies": [
            "button",
            "utils",
            "tokens"
        ],
        "dependencies": [
            "class-variance-authority"
        ]
    },
    "callout": {
        "title": "Callout",
        "description": "Callout — Blueprint-faithful, built on CVA.",
        "tests": {
            "total": 0,
            "a11y": 0,
            "keyboard": 0,
            "behavior": 0
        },
        "rsc": true,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true,
        "axe": true,
        "exports": [
            "Callout"
        ],
        "registryDependencies": [
            "icon",
            "types",
            "utils",
            "tokens"
        ],
        "dependencies": []
    },
    "card": {
        "title": "Card",
        "description": "Card — Blueprint-faithful, built on CVA.",
        "tests": {
            "total": 0,
            "a11y": 0,
            "keyboard": 0,
            "behavior": 0
        },
        "rsc": true,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true,
        "axe": false,
        "exports": [
            "Card"
        ],
        "registryDependencies": [
            "utils",
            "tokens"
        ],
        "dependencies": [
            "class-variance-authority"
        ]
    },
    "card-list": {
        "title": "CardList",
        "description": "CardList — Blueprint-faithful, built on CVA.",
        "tests": {
            "total": 0,
            "a11y": 0,
            "keyboard": 0,
            "behavior": 0
        },
        "rsc": true,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true,
        "axe": true,
        "exports": [
            "CardList"
        ],
        "registryDependencies": [
            "card",
            "utils",
            "tokens"
        ],
        "dependencies": []
    },
    "checkbox": {
        "title": "Checkbox",
        "description": "Checkbox — Blueprint-faithful, built on CVA.",
        "tests": {
            "total": 0,
            "a11y": 0,
            "keyboard": 0,
            "behavior": 0
        },
        "rsc": false,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true,
        "axe": true,
        "exports": [
            "Checkbox"
        ],
        "registryDependencies": [
            "icon",
            "utils",
            "tokens"
        ],
        "dependencies": []
    },
    "collapse": {
        "title": "Collapse",
        "description": "Collapse — Blueprint-faithful, built on CVA.",
        "tests": {
            "total": 0,
            "a11y": 0,
            "keyboard": 0,
            "behavior": 0
        },
        "rsc": false,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true,
        "axe": false,
        "exports": [
            "Collapse"
        ],
        "registryDependencies": [
            "utils",
            "tokens"
        ],
        "dependencies": []
    },
    "context-menu": {
        "title": "ContextMenu",
        "description": "ContextMenu — Blueprint-faithful, built on CVA + Radix.",
        "tests": {
            "total": 3,
            "a11y": 1,
            "keyboard": 2,
            "behavior": 0
        },
        "rsc": false,
        "portal": true,
        "radix": true,
        "polymorphic": true,
        "registry": true,
        "axe": false,
        "exports": [
            "ContextMenu"
        ],
        "registryDependencies": [
            "menu",
            "utils",
            "tokens"
        ],
        "dependencies": [
            "@radix-ui/react-context-menu"
        ]
    },
    "control-base": {
        "title": "ControlBase",
        "description": "ControlBase — Blueprint-faithful, built on CVA.",
        "tests": {
            "total": 0,
            "a11y": 0,
            "keyboard": 0,
            "behavior": 0
        },
        "rsc": true,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true,
        "axe": false,
        "exports": [
            "ControlBase"
        ],
        "registryDependencies": [
            "utils",
            "tokens"
        ],
        "dependencies": []
    },
    "control-card": {
        "title": "ControlCard",
        "description": "ControlCard — Blueprint-faithful, built on CVA.",
        "tests": {
            "total": 0,
            "a11y": 0,
            "keyboard": 0,
            "behavior": 0
        },
        "rsc": false,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true,
        "axe": false,
        "exports": [
            "CheckboxCard",
            "RadioCard",
            "SwitchCard"
        ],
        "registryDependencies": [
            "card",
            "checkbox",
            "radio",
            "switch",
            "utils",
            "tokens"
        ],
        "dependencies": []
    },
    "control-group": {
        "title": "ControlGroup",
        "description": "ControlGroup — Blueprint-faithful, built on CVA.",
        "tests": {
            "total": 12,
            "a11y": 1,
            "keyboard": 0,
            "behavior": 11
        },
        "rsc": true,
        "portal": false,
        "radix": false,
        "polymorphic": true,
        "registry": true,
        "axe": false,
        "exports": [
            "ControlGroup"
        ],
        "registryDependencies": [
            "utils",
            "tokens"
        ],
        "dependencies": [
            "class-variance-authority"
        ]
    },
    "data-table": {
        "title": "DataTable",
        "description": "DataTable — Blueprint-faithful, built on CVA.",
        "tests": {
            "total": 76,
            "a11y": 3,
            "keyboard": 11,
            "behavior": 62
        },
        "rsc": false,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true,
        "axe": false,
        "exports": [
            "DataTable"
        ],
        "registryDependencies": [
            "icon",
            "skeleton",
            "utils",
            "tokens"
        ],
        "dependencies": [
            "@tanstack/react-table",
            "@tanstack/react-virtual"
        ]
    },
    "date-input": {
        "title": "DateInput",
        "description": "DateInput — Blueprint-faithful, built on CVA.",
        "tests": {
            "total": 0,
            "a11y": 0,
            "keyboard": 0,
            "behavior": 0
        },
        "rsc": false,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true,
        "axe": false,
        "exports": [
            "DateInput"
        ],
        "registryDependencies": [
            "date-picker",
            "icon",
            "input-group",
            "popover",
            "time-picker",
            "utils",
            "tokens"
        ],
        "dependencies": []
    },
    "date-picker": {
        "title": "DatePicker",
        "description": "DatePicker — Blueprint-faithful, built on CVA.",
        "tests": {
            "total": 0,
            "a11y": 0,
            "keyboard": 0,
            "behavior": 0
        },
        "rsc": false,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true,
        "axe": false,
        "exports": [
            "DatePicker"
        ],
        "registryDependencies": [
            "html-select",
            "icon",
            "time-picker",
            "utils",
            "tokens"
        ],
        "dependencies": [
            "react-day-picker"
        ]
    },
    "date-range-input": {
        "title": "DateRangeInput",
        "description": "DateRangeInput — Blueprint-faithful, built on CVA.",
        "tests": {
            "total": 8,
            "a11y": 2,
            "keyboard": 0,
            "behavior": 6
        },
        "rsc": false,
        "portal": false,
        "radix": false,
        "polymorphic": true,
        "registry": true,
        "axe": false,
        "exports": [
            "DateRangeInput"
        ],
        "registryDependencies": [
            "date-range-picker",
            "input-group",
            "popover",
            "utils",
            "tokens"
        ],
        "dependencies": []
    },
    "date-range-picker": {
        "title": "DateRangePicker",
        "description": "DateRangePicker — Blueprint-faithful, built on CVA.",
        "tests": {
            "total": 8,
            "a11y": 1,
            "keyboard": 0,
            "behavior": 7
        },
        "rsc": false,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true,
        "axe": false,
        "exports": [
            "DateRangePicker"
        ],
        "registryDependencies": [
            "html-select",
            "icon",
            "utils",
            "tokens"
        ],
        "dependencies": [
            "react-day-picker"
        ]
    },
    "dialog": {
        "title": "Dialog",
        "description": "Dialog — Blueprint-faithful, built on CVA + Radix.",
        "tests": {
            "total": 11,
            "a11y": 0,
            "keyboard": 0,
            "behavior": 11
        },
        "rsc": false,
        "portal": true,
        "radix": true,
        "polymorphic": true,
        "registry": true,
        "axe": true,
        "exports": [
            "Dialog",
            "DialogBody",
            "DialogFooter"
        ],
        "registryDependencies": [
            "button",
            "icon",
            "utils",
            "tokens"
        ],
        "dependencies": [
            "@radix-ui/react-dialog"
        ]
    },
    "divider": {
        "title": "Divider",
        "description": "Divider — Blueprint-faithful, built on CVA.",
        "tests": {
            "total": 0,
            "a11y": 0,
            "keyboard": 0,
            "behavior": 0
        },
        "rsc": true,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true,
        "axe": false,
        "exports": [
            "Divider"
        ],
        "registryDependencies": [
            "utils",
            "tokens"
        ],
        "dependencies": [
            "class-variance-authority"
        ]
    },
    "drawer": {
        "title": "Drawer",
        "description": "Drawer — Blueprint-faithful, built on CVA + Radix.",
        "tests": {
            "total": 0,
            "a11y": 0,
            "keyboard": 0,
            "behavior": 0
        },
        "rsc": false,
        "portal": true,
        "radix": true,
        "polymorphic": true,
        "registry": true,
        "axe": true,
        "exports": [
            "Drawer",
            "DrawerBody",
            "DrawerFooter"
        ],
        "registryDependencies": [
            "button",
            "icon",
            "utils",
            "tokens"
        ],
        "dependencies": [
            "@radix-ui/react-dialog"
        ]
    },
    "editable-text": {
        "title": "EditableText",
        "description": "EditableText — Blueprint-faithful, built on CVA.",
        "tests": {
            "total": 10,
            "a11y": 0,
            "keyboard": 4,
            "behavior": 6
        },
        "rsc": false,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true,
        "axe": false,
        "exports": [
            "EditableText"
        ],
        "registryDependencies": [
            "types",
            "utils",
            "tokens"
        ],
        "dependencies": []
    },
    "entity-title": {
        "title": "EntityTitle",
        "description": "EntityTitle — Blueprint-faithful, built on CVA.",
        "tests": {
            "total": 0,
            "a11y": 0,
            "keyboard": 0,
            "behavior": 0
        },
        "rsc": true,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true,
        "axe": false,
        "exports": [
            "EntityTitle"
        ],
        "registryDependencies": [
            "icon",
            "skeleton",
            "utils",
            "tokens"
        ],
        "dependencies": []
    },
    "file-input": {
        "title": "FileInput",
        "description": "FileInput — Blueprint-faithful, built on CVA.",
        "tests": {
            "total": 9,
            "a11y": 4,
            "keyboard": 0,
            "behavior": 5
        },
        "rsc": false,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true,
        "axe": false,
        "exports": [
            "FileInput"
        ],
        "registryDependencies": [
            "utils",
            "tokens"
        ],
        "dependencies": []
    },
    "form-group": {
        "title": "FormGroup",
        "description": "FormGroup — Blueprint-faithful, built on CVA.",
        "tests": {
            "total": 8,
            "a11y": 4,
            "keyboard": 0,
            "behavior": 4
        },
        "rsc": true,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true,
        "axe": false,
        "exports": [
            "Label",
            "FormGroup"
        ],
        "registryDependencies": [
            "types",
            "utils",
            "tokens"
        ],
        "dependencies": []
    },
    "hotkeys": {
        "title": "Hotkeys",
        "description": "Hotkeys — Blueprint-faithful, built on CVA.",
        "tests": {
            "total": 16,
            "a11y": 0,
            "keyboard": 4,
            "behavior": 12
        },
        "rsc": false,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true,
        "axe": false,
        "exports": [
            "KeyCombo",
            "HotkeysDialog",
            "HotkeysProvider"
        ],
        "registryDependencies": [
            "dialog",
            "icon",
            "utils",
            "tokens"
        ],
        "dependencies": []
    },
    "html-select": {
        "title": "HTMLSelect",
        "description": "HTMLSelect — Blueprint-faithful, built on CVA.",
        "tests": {
            "total": 0,
            "a11y": 0,
            "keyboard": 0,
            "behavior": 0
        },
        "rsc": true,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true,
        "axe": false,
        "exports": [
            "HTMLSelect"
        ],
        "registryDependencies": [
            "icon",
            "utils",
            "tokens"
        ],
        "dependencies": []
    },
    "html-table": {
        "title": "HTMLTable",
        "description": "HTMLTable — Blueprint-faithful, built on CVA.",
        "tests": {
            "total": 10,
            "a11y": 1,
            "keyboard": 0,
            "behavior": 9
        },
        "rsc": true,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true,
        "axe": true,
        "exports": [
            "HTMLTable"
        ],
        "registryDependencies": [
            "utils",
            "tokens"
        ],
        "dependencies": [
            "class-variance-authority"
        ]
    },
    "icon": {
        "title": "Icon",
        "description": "Icon — Blueprint-faithful, built on CVA.",
        "tests": {
            "total": 0,
            "a11y": 0,
            "keyboard": 0,
            "behavior": 0
        },
        "rsc": true,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true,
        "axe": false,
        "exports": [
            "Icon"
        ],
        "registryDependencies": [
            "types",
            "utils",
            "tokens"
        ],
        "dependencies": []
    },
    "input-group": {
        "title": "InputGroup",
        "description": "InputGroup — Blueprint-faithful, built on CVA.",
        "tests": {
            "total": 0,
            "a11y": 0,
            "keyboard": 0,
            "behavior": 0
        },
        "rsc": true,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true,
        "axe": true,
        "exports": [
            "InputGroup"
        ],
        "registryDependencies": [
            "icon",
            "types",
            "utils",
            "tokens"
        ],
        "dependencies": [
            "class-variance-authority"
        ]
    },
    "link": {
        "title": "Link",
        "description": "Link — Blueprint-faithful, built on CVA.",
        "tests": {
            "total": 0,
            "a11y": 0,
            "keyboard": 0,
            "behavior": 0
        },
        "rsc": true,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true,
        "axe": false,
        "exports": [
            "Link"
        ],
        "registryDependencies": [
            "utils",
            "tokens"
        ],
        "dependencies": [
            "class-variance-authority"
        ]
    },
    "menu": {
        "title": "Menu",
        "description": "Menu — Blueprint-faithful, built on CVA.",
        "tests": {
            "total": 6,
            "a11y": 6,
            "keyboard": 0,
            "behavior": 0
        },
        "rsc": false,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true,
        "axe": true,
        "exports": [
            "Menu",
            "MenuItem",
            "MenuDivider"
        ],
        "registryDependencies": [
            "icon",
            "types",
            "utils",
            "tokens"
        ],
        "dependencies": []
    },
    "multi-select": {
        "title": "MultiSelect",
        "description": "MultiSelect — Blueprint-faithful, built on CVA.",
        "tests": {
            "total": 3,
            "a11y": 2,
            "keyboard": 0,
            "behavior": 1
        },
        "rsc": false,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true,
        "axe": true,
        "exports": [
            "MultiSelect"
        ],
        "registryDependencies": [
            "icon",
            "menu",
            "popover",
            "select",
            "tag",
            "types",
            "utils",
            "tokens"
        ],
        "dependencies": []
    },
    "multistep-dialog": {
        "title": "MultistepDialog",
        "description": "MultistepDialog — Blueprint-faithful, built on CVA.",
        "tests": {
            "total": 12,
            "a11y": 1,
            "keyboard": 1,
            "behavior": 10
        },
        "rsc": false,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true,
        "axe": true,
        "exports": [
            "DialogStep",
            "MultistepDialog"
        ],
        "registryDependencies": [
            "button",
            "dialog",
            "utils",
            "tokens"
        ],
        "dependencies": []
    },
    "navbar": {
        "title": "Navbar",
        "description": "Navbar — Blueprint-faithful, built on CVA.",
        "tests": {
            "total": 9,
            "a11y": 1,
            "keyboard": 0,
            "behavior": 8
        },
        "rsc": true,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true,
        "axe": false,
        "exports": [
            "Navbar",
            "NavbarGroup",
            "NavbarHeading",
            "NavbarDivider"
        ],
        "registryDependencies": [
            "utils",
            "tokens"
        ],
        "dependencies": []
    },
    "non-ideal-state": {
        "title": "NonIdealState",
        "description": "NonIdealState — Blueprint-faithful, built on CVA.",
        "tests": {
            "total": 0,
            "a11y": 0,
            "keyboard": 0,
            "behavior": 0
        },
        "rsc": true,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true,
        "axe": false,
        "exports": [
            "NonIdealState"
        ],
        "registryDependencies": [
            "icon",
            "utils",
            "tokens"
        ],
        "dependencies": [
            "class-variance-authority"
        ]
    },
    "numeric-input": {
        "title": "NumericInput",
        "description": "NumericInput — Blueprint-faithful, built on CVA.",
        "tests": {
            "total": 4,
            "a11y": 2,
            "keyboard": 1,
            "behavior": 1
        },
        "rsc": false,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true,
        "axe": true,
        "exports": [
            "NumericInput"
        ],
        "registryDependencies": [
            "icon",
            "input-group",
            "utils",
            "tokens"
        ],
        "dependencies": []
    },
    "omnibar": {
        "title": "Omnibar",
        "description": "Omnibar — Blueprint-faithful, built on CVA.",
        "tests": {
            "total": 4,
            "a11y": 1,
            "keyboard": 2,
            "behavior": 1
        },
        "rsc": false,
        "portal": true,
        "radix": false,
        "polymorphic": false,
        "registry": true,
        "axe": false,
        "exports": [
            "Omnibar"
        ],
        "registryDependencies": [
            "icon",
            "input-group",
            "menu",
            "select",
            "utils",
            "tokens"
        ],
        "dependencies": []
    },
    "overflow-list": {
        "title": "OverflowList",
        "description": "OverflowList — Blueprint-faithful, built on CVA.",
        "tests": {
            "total": 7,
            "a11y": 1,
            "keyboard": 0,
            "behavior": 6
        },
        "rsc": false,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true,
        "axe": false,
        "exports": [
            "OverflowList"
        ],
        "registryDependencies": [
            "resize-sensor",
            "utils",
            "tokens"
        ],
        "dependencies": []
    },
    "panel-stack": {
        "title": "PanelStack",
        "description": "PanelStack — Blueprint-faithful, built on CVA.",
        "tests": {
            "total": 9,
            "a11y": 0,
            "keyboard": 0,
            "behavior": 9
        },
        "rsc": false,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true,
        "axe": false,
        "exports": [
            "PanelStack"
        ],
        "registryDependencies": [
            "button",
            "icon",
            "utils",
            "tokens"
        ],
        "dependencies": []
    },
    "popover": {
        "title": "Popover",
        "description": "Popover — Blueprint-faithful, built on CVA + Radix.",
        "tests": {
            "total": 3,
            "a11y": 0,
            "keyboard": 1,
            "behavior": 2
        },
        "rsc": false,
        "portal": true,
        "radix": true,
        "polymorphic": true,
        "registry": true,
        "axe": true,
        "exports": [
            "Popover",
            "MenuPopover"
        ],
        "registryDependencies": [
            "utils",
            "tokens"
        ],
        "dependencies": [
            "@radix-ui/react-popover"
        ]
    },
    "portal": {
        "title": "Portal",
        "description": "Portal — Blueprint-faithful, built on CVA.",
        "tests": {
            "total": 8,
            "a11y": 1,
            "keyboard": 0,
            "behavior": 7
        },
        "rsc": false,
        "portal": true,
        "radix": false,
        "polymorphic": false,
        "registry": true,
        "axe": false,
        "exports": [
            "PortalProvider",
            "Portal"
        ],
        "registryDependencies": [
            "utils",
            "tokens"
        ],
        "dependencies": []
    },
    "progress-bar": {
        "title": "ProgressBar",
        "description": "ProgressBar — Blueprint-faithful, built on CVA.",
        "tests": {
            "total": 0,
            "a11y": 0,
            "keyboard": 0,
            "behavior": 0
        },
        "rsc": true,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true,
        "axe": false,
        "exports": [
            "ProgressBar"
        ],
        "registryDependencies": [
            "types",
            "utils",
            "tokens"
        ],
        "dependencies": []
    },
    "radio": {
        "title": "Radio",
        "description": "Radio — Blueprint-faithful, built on CVA.",
        "tests": {
            "total": 10,
            "a11y": 2,
            "keyboard": 0,
            "behavior": 8
        },
        "rsc": false,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true,
        "axe": true,
        "exports": [
            "RadioGroup",
            "Radio"
        ],
        "registryDependencies": [
            "utils",
            "tokens"
        ],
        "dependencies": []
    },
    "resize-sensor": {
        "title": "ResizeSensor",
        "description": "ResizeSensor — Blueprint-faithful, built on CVA.",
        "tests": {
            "total": 6,
            "a11y": 0,
            "keyboard": 0,
            "behavior": 6
        },
        "rsc": false,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true,
        "axe": false,
        "exports": [
            "ResizeSensor"
        ],
        "registryDependencies": [
            "tokens"
        ],
        "dependencies": []
    },
    "section": {
        "title": "Section",
        "description": "Section — Blueprint-faithful, built on CVA.",
        "tests": {
            "total": 0,
            "a11y": 0,
            "keyboard": 0,
            "behavior": 0
        },
        "rsc": false,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true,
        "axe": false,
        "exports": [
            "Section",
            "SectionCard"
        ],
        "registryDependencies": [
            "card",
            "collapse",
            "icon",
            "text",
            "utils",
            "tokens"
        ],
        "dependencies": []
    },
    "segmented-control": {
        "title": "SegmentedControl",
        "description": "SegmentedControl — Blueprint-faithful, built on CVA.",
        "tests": {
            "total": 0,
            "a11y": 0,
            "keyboard": 0,
            "behavior": 0
        },
        "rsc": false,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true,
        "axe": false,
        "exports": [
            "SegmentedControl"
        ],
        "registryDependencies": [
            "button",
            "icon",
            "types",
            "utils",
            "tokens"
        ],
        "dependencies": [
            "class-variance-authority"
        ]
    },
    "select": {
        "title": "Select",
        "description": "Select — Blueprint-faithful, built on CVA.",
        "tests": {
            "total": 7,
            "a11y": 4,
            "keyboard": 1,
            "behavior": 2
        },
        "rsc": false,
        "portal": false,
        "radix": false,
        "polymorphic": true,
        "registry": true,
        "axe": false,
        "exports": [
            "Select"
        ],
        "registryDependencies": [
            "icon",
            "input-group",
            "menu",
            "popover",
            "utils",
            "tokens"
        ],
        "dependencies": []
    },
    "skeleton": {
        "title": "Skeleton",
        "description": "Skeleton — Blueprint-faithful, built on CVA.",
        "tests": {
            "total": 0,
            "a11y": 0,
            "keyboard": 0,
            "behavior": 0
        },
        "rsc": true,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true,
        "axe": false,
        "exports": [
            "Skeleton"
        ],
        "registryDependencies": [
            "skeleton",
            "utils",
            "tokens"
        ],
        "dependencies": []
    },
    "slider": {
        "title": "Slider",
        "description": "Slider — Blueprint-faithful, built on CVA + Radix.",
        "tests": {
            "total": 0,
            "a11y": 0,
            "keyboard": 0,
            "behavior": 0
        },
        "rsc": false,
        "portal": false,
        "radix": true,
        "polymorphic": false,
        "registry": true,
        "axe": true,
        "exports": [
            "Slider"
        ],
        "registryDependencies": [
            "types",
            "utils",
            "tokens"
        ],
        "dependencies": [
            "@radix-ui/react-slider"
        ]
    },
    "spinner": {
        "title": "Spinner",
        "description": "Spinner — Blueprint-faithful, built on CVA.",
        "tests": {
            "total": 0,
            "a11y": 0,
            "keyboard": 0,
            "behavior": 0
        },
        "rsc": true,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true,
        "axe": false,
        "exports": [
            "Spinner"
        ],
        "registryDependencies": [
            "types",
            "utils",
            "tokens"
        ],
        "dependencies": []
    },
    "suggest": {
        "title": "Suggest",
        "description": "Suggest — Blueprint-faithful, built on CVA.",
        "tests": {
            "total": 4,
            "a11y": 2,
            "keyboard": 1,
            "behavior": 1
        },
        "rsc": false,
        "portal": false,
        "radix": false,
        "polymorphic": true,
        "registry": true,
        "axe": true,
        "exports": [
            "Suggest"
        ],
        "registryDependencies": [
            "input-group",
            "menu",
            "popover",
            "select",
            "utils",
            "tokens"
        ],
        "dependencies": []
    },
    "switch": {
        "title": "Switch",
        "description": "Switch — Blueprint-faithful, built on CVA.",
        "tests": {
            "total": 0,
            "a11y": 0,
            "keyboard": 0,
            "behavior": 0
        },
        "rsc": false,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true,
        "axe": true,
        "exports": [
            "Switch"
        ],
        "registryDependencies": [
            "utils",
            "tokens"
        ],
        "dependencies": []
    },
    "tabs": {
        "title": "Tabs",
        "description": "Tabs — Blueprint-faithful, built on CVA + Radix.",
        "tests": {
            "total": 17,
            "a11y": 2,
            "keyboard": 5,
            "behavior": 10
        },
        "rsc": false,
        "portal": false,
        "radix": true,
        "polymorphic": false,
        "registry": true,
        "axe": true,
        "exports": [
            "Tabs",
            "Tab"
        ],
        "registryDependencies": [
            "icon",
            "utils",
            "tokens"
        ],
        "dependencies": [
            "@radix-ui/react-tabs"
        ]
    },
    "tag": {
        "title": "Tag",
        "description": "Tag — Blueprint-faithful, built on CVA.",
        "tests": {
            "total": 0,
            "a11y": 0,
            "keyboard": 0,
            "behavior": 0
        },
        "rsc": false,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true,
        "axe": true,
        "exports": [
            "Tag"
        ],
        "registryDependencies": [
            "icon",
            "types",
            "utils",
            "tokens"
        ],
        "dependencies": []
    },
    "tag-input": {
        "title": "TagInput",
        "description": "TagInput — Blueprint-faithful, built on CVA.",
        "tests": {
            "total": 0,
            "a11y": 0,
            "keyboard": 0,
            "behavior": 0
        },
        "rsc": false,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true,
        "axe": false,
        "exports": [
            "TagInput"
        ],
        "registryDependencies": [
            "icon",
            "tag",
            "types",
            "utils",
            "tokens"
        ],
        "dependencies": []
    },
    "text": {
        "title": "Text",
        "description": "Text — Blueprint-faithful, built on CVA.",
        "tests": {
            "total": 0,
            "a11y": 0,
            "keyboard": 0,
            "behavior": 0
        },
        "rsc": false,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true,
        "axe": false,
        "exports": [
            "Text"
        ],
        "registryDependencies": [
            "utils",
            "tokens"
        ],
        "dependencies": [
            "class-variance-authority"
        ]
    },
    "text-area": {
        "title": "TextArea",
        "description": "TextArea — Blueprint-faithful, built on CVA.",
        "tests": {
            "total": 9,
            "a11y": 1,
            "keyboard": 0,
            "behavior": 8
        },
        "rsc": false,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true,
        "axe": false,
        "exports": [
            "TextArea"
        ],
        "registryDependencies": [
            "types",
            "utils",
            "tokens"
        ],
        "dependencies": [
            "class-variance-authority"
        ]
    },
    "time-picker": {
        "title": "TimePicker",
        "description": "TimePicker — Blueprint-faithful, built on CVA.",
        "tests": {
            "total": 0,
            "a11y": 0,
            "keyboard": 0,
            "behavior": 0
        },
        "rsc": false,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true,
        "axe": true,
        "exports": [
            "TimePicker"
        ],
        "registryDependencies": [
            "html-select",
            "icon",
            "utils",
            "tokens"
        ],
        "dependencies": []
    },
    "timezone-select": {
        "title": "TimezoneSelect",
        "description": "TimezoneSelect — Blueprint-faithful, built on CVA.",
        "tests": {
            "total": 8,
            "a11y": 2,
            "keyboard": 0,
            "behavior": 6
        },
        "rsc": false,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true,
        "axe": false,
        "exports": [
            "TimezoneSelect",
            "MINIMAL_IANA_CODES"
        ],
        "registryDependencies": [
            "button",
            "icon",
            "menu",
            "select",
            "tokens"
        ],
        "dependencies": []
    },
    "toast": {
        "title": "Toast",
        "description": "Toast — Blueprint-faithful, built on CVA + Radix.",
        "tests": {
            "total": 0,
            "a11y": 0,
            "keyboard": 0,
            "behavior": 0
        },
        "rsc": false,
        "portal": false,
        "radix": true,
        "polymorphic": true,
        "registry": true,
        "axe": false,
        "exports": [
            "Toast",
            "ToastProvider",
            "Toaster"
        ],
        "registryDependencies": [
            "icon",
            "types",
            "utils",
            "tokens"
        ],
        "dependencies": [
            "@radix-ui/react-toast"
        ]
    },
    "tooltip": {
        "title": "Tooltip",
        "description": "Tooltip — Blueprint-faithful, built on CVA + Radix.",
        "tests": {
            "total": 0,
            "a11y": 0,
            "keyboard": 0,
            "behavior": 0
        },
        "rsc": false,
        "portal": true,
        "radix": true,
        "polymorphic": true,
        "registry": true,
        "axe": false,
        "exports": [
            "TooltipProvider",
            "Tooltip"
        ],
        "registryDependencies": [
            "types",
            "utils",
            "tokens"
        ],
        "dependencies": [
            "@radix-ui/react-tooltip"
        ]
    },
    "tree": {
        "title": "Tree",
        "description": "Tree — Blueprint-faithful, built on CVA.",
        "tests": {
            "total": 0,
            "a11y": 0,
            "keyboard": 0,
            "behavior": 0
        },
        "rsc": false,
        "portal": false,
        "radix": false,
        "polymorphic": false,
        "registry": true,
        "axe": false,
        "exports": [
            "Tree"
        ],
        "registryDependencies": [
            "collapse",
            "icon",
            "utils",
            "tokens"
        ],
        "dependencies": []
    }
};
